/*
 * This file is part of SEVino.
 *
 * SEVino is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * SEVino is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with SEVino.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Copyright 2008, 2009, 2010, 2011, 2012 Alpen-Adria-Universitaet Klagenfurt, Markus Waltl.
 */
package br.ufes.inf.lprm.sensoryeffect.renderer.metadata.parser.mpegv;

import java.awt.Color;
import java.util.Vector;
import java.util.Hashtable;

/**
 * Class defining all classification schemes of MPEG-V
 * @author Markus Waltl
 *
 */

/**
 * Modified by
 * 
 * @author Estevao Bissoli Saleme 
 * @version 2.0
 */	

public class ClassificationScheme {
	// A.2.1	ColorCS
	private static Hashtable<String, Color> colorTable_ = new Hashtable<String, Color>();
	
	public final static String COLORURIBASE = "urn:mpeg:mpeg-v:01-SI-ColorCS-NS";	
	public final static String COLOR_ALICE_BLUE = COLORURIBASE + ":alice_blue";
	public final static String COLOR_ALIZARIN = COLORURIBASE + ":alizarin";
	public final static String COLOR_AMARANTH = COLORURIBASE + ":amaranth";
	public final static String COLOR_AMARANTH_PINK = COLORURIBASE + ":amaranth_pink";
	public final static String COLOR_AMBER = COLORURIBASE + ":amber";
	public final static String COLOR_AMETHYST = COLORURIBASE + ":amethyst";
	public final static String COLOR_APRICOT = COLORURIBASE + ":apricot";
	public final static String COLOR_AQUA = COLORURIBASE + ":aqua";
	public final static String COLOR_AQUAMARINE = COLORURIBASE + ":aquamarine";
	public final static String COLOR_ARMY_GREEN = COLORURIBASE + ":army_green";
	public final static String COLOR_ASPARAGUS = COLORURIBASE + ":asparagus";
	public final static String COLOR_ATOMIC_TANGERINE = COLORURIBASE + ":atomic_tangerine";
	public final static String COLOR_AUBURN = COLORURIBASE + ":auburn";
	public final static String COLOR_AZURE_COLOR_WHEEL = COLORURIBASE + ":azure_color_wheel";
	public final static String COLOR_AZURE_WEB = COLORURIBASE + ":azure_web";
	public final static String COLOR_BABY_BLUE = COLORURIBASE + ":baby_blue";
	public final static String COLOR_BEIGE = COLORURIBASE + ":beige";
	public final static String COLOR_BISTRE = COLORURIBASE + ":bistre";
	public final static String COLOR_BLACK = COLORURIBASE + ":black";
	public final static String COLOR_BLUE = COLORURIBASE + ":blue";
	public final static String COLOR_BLUE_PIGMENT = COLORURIBASE + ":blue_pigment";
	public final static String COLOR_BLUE_RYB = COLORURIBASE + ":blue_ryb";
	public final static String COLOR_BLUE_GREEN = COLORURIBASE + ":blue-green";
	public final static String COLOR_BLUE_VIOLET = COLORURIBASE + ":blue-violet";
	public final static String COLOR_BONDI_BLUE = COLORURIBASE + ":bondi_blue";
	public final static String COLOR_BRASS = COLORURIBASE + ":brass";
	public final static String COLOR_BRIGHT_GREEN = COLORURIBASE + ":bright_green";
	public final static String COLOR_BRIGHT_PINK = COLORURIBASE + ":bright_pink";
	public final static String COLOR_BRIGHT_TURQUOISE = COLORURIBASE + ":bright_turquoise";
	public final static String COLOR_BRILLIANT_ROSE = COLORURIBASE + ":brilliant_rose";
	public final static String COLOR_BRINK_PINK = COLORURIBASE + ":brink_pink";
	public final static String COLOR_BRONZE = COLORURIBASE + ":bronze"; 
	public final static String COLOR_BROWN = COLORURIBASE + ":brown";
	public final static String COLOR_BUFF = COLORURIBASE + ":buff";
	public final static String COLOR_BURGUNDY = COLORURIBASE + ":burgundy";
	public final static String COLOR_BURNT_ORANGE = COLORURIBASE + ":burnt_orange";
	public final static String COLOR_BURNT_SIENNA = COLORURIBASE + ":burnt_sienna";
	public final static String COLOR_BURNT_UMBER = COLORURIBASE + ":burnt_umber";
	public final static String COLOR_CAMOUFLAGE_GREEN = COLORURIBASE + ":camouflage_green";
	public final static String COLOR_CAPUT_MORTUUM = COLORURIBASE + ":caput_mortuum";
	public final static String COLOR_CARDINAL = COLORURIBASE + ":cardinal";
	public final static String COLOR_CARMINE = COLORURIBASE + ":carmine";
	public final static String COLOR_CARMINE_PINK = COLORURIBASE + ":carmine_pink";
	public final static String COLOR_CARNATION_PINK = COLORURIBASE + ":carnation_pink";
	public final static String COLOR_CAROLINA_BLUE = COLORURIBASE + ":carolina_blue";
	public final static String COLOR_CARROT_ORANGE = COLORURIBASE + ":carrot_orange";
	public final static String COLOR_CELADON = COLORURIBASE + ":celadon";
	public final static String COLOR_CERISE = COLORURIBASE + ":cerise";
	public final static String COLOR_CERISE_PINK = COLORURIBASE + ":cerise_pink";
	public final static String COLOR_CERULEAN = COLORURIBASE + ":cerulean";
	public final static String COLOR_CERULEAN_BLUE = COLORURIBASE + ":cerulean_blue";
	public final static String COLOR_CHAMPAGNE = COLORURIBASE + ":champagne";
	public final static String COLOR_CHARCOAL = COLORURIBASE + ":charcoal";
	public final static String COLOR_CHARTREUSE_TRADITIONAL = COLORURIBASE + ":chartreuse_traditional";
	public final static String COLOR_CHARTREUSE_WEB = COLORURIBASE + ":chartreuse_web";
	public final static String COLOR_CHERRY_BLOSSOM_PINK = COLORURIBASE + ":cherry_blossom_pink";
	public final static String COLOR_CHESTNUT = COLORURIBASE + ":chestnut";
	public final static String COLOR_CHOCOLATE = COLORURIBASE + ":chocolate";
	public final static String COLOR_CINNABAR = COLORURIBASE + ":cinnabar";
	public final static String COLOR_CINNAMON = COLORURIBASE + ":cinnamon";
	public final static String COLOR_COBALT = COLORURIBASE + ":cobalt";
	public final static String COLOR_COLUMBIA_BLUE = COLORURIBASE + ":columbia_blue";
	public final static String COLOR_COPPER = COLORURIBASE + ":copper";
	public final static String COLOR_COPPER_ROSE = COLORURIBASE + ":copper_rose";
	public final static String COLOR_CORAL = COLORURIBASE + ":coral";
	public final static String COLOR_CORAL_PINK = COLORURIBASE + ":coral_pink";
	public final static String COLOR_CORAL_RED = COLORURIBASE + ":coral_red";
	public final static String COLOR_CORN = COLORURIBASE + ":corn";
	public final static String COLOR_CORNFLOWER_BLUE = COLORURIBASE + ":cornflower_blue";
	public final static String COLOR_COSMIC_LATTE = COLORURIBASE + ":cosmic_latte";
	public final static String COLOR_CREAM = COLORURIBASE + ":cream";
	public final static String COLOR_CRIMSON = COLORURIBASE + ":crimson";
	public final static String COLOR_CYAN = COLORURIBASE + ":cyan";
	public final static String COLOR_CYAN_PROCESS = COLORURIBASE + ":cyan_process";
	public final static String COLOR_DARK_BLUE = COLORURIBASE + ":dark_blue";
	public final static String COLOR_DARK_BROWN = COLORURIBASE + ":dark_brown";
	public final static String COLOR_DARK_CERULEAN = COLORURIBASE + ":dark_cerulean";
	public final static String COLOR_DARK_CHESTNUT = COLORURIBASE + ":dark_chestnut";
	public final static String COLOR_DARK_CORAL = COLORURIBASE + ":dark_coral";
	public final static String COLOR_DARK_GOLDENROD = COLORURIBASE + ":dark_goldenrod";
	public final static String COLOR_DARK_GREEN = COLORURIBASE + ":dark_green";
	public final static String COLOR_DARK_KHAKI = COLORURIBASE + ":dark_khaki";
	public final static String COLOR_DARK_MAGENTA = COLORURIBASE + ":dark_magenta";
	public final static String COLOR_DARK_PASTEL_GREEN = COLORURIBASE + ":dark_pastel_green";
	public final static String COLOR_DARK_PINK = COLORURIBASE + ":dark_pink";
	public final static String COLOR_DARK_SCARLET = COLORURIBASE + ":dark_scarlet";
	public final static String COLOR_DARK_SALMON = COLORURIBASE + ":dark_salmon";
	public final static String COLOR_DARK_SLATE_GRAY = COLORURIBASE + ":dark_slate_gray";
	public final static String COLOR_DARK_SPRING_GREEN = COLORURIBASE + ":dark_spring_green";
	public final static String COLOR_DARK_TAN = COLORURIBASE + ":dark_tan";
	public final static String COLOR_DARK_TURQUOISE = COLORURIBASE + ":dark_turquoise";
	public final static String COLOR_DARK_VIOLET = COLORURIBASE + ":dark_violet";
	public final static String COLOR_DEEP_CARMINE_PINK = COLORURIBASE + ":deep_carmine_pink";
	public final static String COLOR_DEEP_CERISE = COLORURIBASE + ":deep_cerise";
	public final static String COLOR_DEEP_CHESTNUT = COLORURIBASE + ":deep_chestnut";
	public final static String COLOR_DEEP_FUCHSIA = COLORURIBASE + ":deep_fuchsia";
	public final static String COLOR_DEEP_LILAC = COLORURIBASE + ":deep_lilac";
	public final static String COLOR_DEEP_MAGENTA = COLORURIBASE + ":deep_magenta";
	public final static String COLOR_DEEP_PEACH = COLORURIBASE + ":deep_peach";
	public final static String COLOR_DEEP_PINK = COLORURIBASE + ":deep_pink";
	public final static String COLOR_DENIM = COLORURIBASE + ":denim";
	public final static String COLOR_DODGER_BLUE = COLORURIBASE + ":dodger_blue";
	public final static String COLOR_ECRU = COLORURIBASE + ":ecru";
	public final static String COLOR_EGYPTIAN_BLUE = COLORURIBASE + ":egyptian_blue";
	public final static String COLOR_ELECTRIC_BLUE = COLORURIBASE + ":electric_blue";
	public final static String COLOR_ELECTRIC_GREEN_X11_GREEN = COLORURIBASE + ":electric_green_x11_green";
	public final static String COLOR_ELECTRIC_INDIGO = COLORURIBASE + ":electric_indigo";
	public final static String COLOR_ELECTRIC_LIME = COLORURIBASE + ":electric_lime";
	public final static String COLOR_ELECTRIC_PURPLE = COLORURIBASE + ":electric_purple";
	public final static String COLOR_EMERALD = COLORURIBASE + ":emerald";
	public final static String COLOR_EGGPLANT = COLORURIBASE + ":eggplant";
	public final static String COLOR_FALU_RED = COLORURIBASE + ":falu_red";
	public final static String COLOR_FERN_GREEN = COLORURIBASE + ":fern_green";
	public final static String COLOR_FIREBRICK = COLORURIBASE + ":firebrick";
	public final static String COLOR_FLAX = COLORURIBASE + ":flax";
	public final static String COLOR_FOREST_GREEN = COLORURIBASE + ":forest_green";
	public final static String COLOR_FRENCH_ROSE = COLORURIBASE + ":french_rose";
	public final static String COLOR_FUCHSIA = COLORURIBASE + ":fuchsia";
	public final static String COLOR_FUCHSIA_PINK = COLORURIBASE + ":fuchsia_pink";
	public final static String COLOR_GAMBOGE = COLORURIBASE + ":gamboge";
	public final static String COLOR_GOLD_METALLIC = COLORURIBASE + ":gold_metallic";
	public final static String COLOR_GOLD_WEB_GOLDEN = COLORURIBASE + ":gold_web_golden";
	public final static String COLOR_GOLDEN_BROWN = COLORURIBASE + ":golden_brown";
	public final static String COLOR_GOLDEN_YELLOW = COLORURIBASE + ":golden_yellow";
	public final static String COLOR_GOLDENROD = COLORURIBASE + ":goldenrod";
	public final static String COLOR_GREY_ASPARAGUS = COLORURIBASE + ":grey-asparagus";
	public final static String COLOR_GREEN_COLOR_WHEEL_X11_GREEN = COLORURIBASE + ":green_color_wheel_x11_green";
	public final static String COLOR_GREEN_HTMLCSS_GREEN = COLORURIBASE + ":green_html/css_green";
	public final static String COLOR_GREEN_PIGMENT = COLORURIBASE + ":green_pigment";
	public final static String COLOR_GREEN_RYB = COLORURIBASE + ":green_ryb";
	public final static String COLOR_GREEN_YELLOW = COLORURIBASE + ":green-yellow";
	public final static String COLOR_GREY = COLORURIBASE + ":grey";
	public final static String COLOR_HAN_PURPLE = COLORURIBASE + ":han_purple";
	public final static String COLOR_HARLEQUIN = COLORURIBASE + ":harlequin";
	public final static String COLOR_HELIOTROPE = COLORURIBASE + ":heliotrope";
	public final static String COLOR_HOLLYWOOD_CERISE = COLORURIBASE + ":hollywood_cerise";
	public final static String COLOR_HOT_MAGENTA = COLORURIBASE + ":hot_magenta";
	public final static String COLOR_HOT_PINK = COLORURIBASE + ":hot_pink";
	public final static String COLOR_INDIGO_DYE = COLORURIBASE + ":indigo_dye";
	public final static String COLOR_INDIGO_WEB = COLORURIBASE + ":indigo_web";
	public final static String COLOR_INTERNATIONAL_KLEIN_BLUE = COLORURIBASE + ":international_klein_blue";
	public final static String COLOR_INTERNATIONAL_ORANGE = COLORURIBASE + ":international_orange";
	public final static String COLOR_ISLAMIC_GREEN = COLORURIBASE + ":islamic_green";
	public final static String COLOR_IVORY = COLORURIBASE + ":ivory";
	public final static String COLOR_JADE = COLORURIBASE + ":jade";
	public final static String COLOR_KELLY_GREEN = COLORURIBASE + ":kelly_green";
	public final static String COLOR_KHAKI = COLORURIBASE + ":khaki";
	public final static String COLOR_KHAKI_X11_LIGHT_KHAKI = COLORURIBASE + ":khaki_x11_light_khaki";
	public final static String COLOR_LAVENDER_FLORAL = COLORURIBASE + ":lavender_floral";
	public final static String COLOR_LAVENDER_WEB = COLORURIBASE + ":lavender_web";
	public final static String COLOR_LAVENDER_BLUE = COLORURIBASE + ":lavender_blue";
	public final static String COLOR_LAVENDER_BLUSH = COLORURIBASE + ":lavender_blush";
	public final static String COLOR_LAVENDER_GREY = COLORURIBASE + ":lavender_grey";
	public final static String COLOR_LAVENDER_MAGENTA = COLORURIBASE + ":lavender_magenta";
	public final static String COLOR_LAVENDER_PINK = COLORURIBASE + ":lavender_pink";
	public final static String COLOR_LAVENDER_PURPLE = COLORURIBASE + ":lavender_purple";
	public final static String COLOR_LAVENDER_ROSE = COLORURIBASE + ":lavender_rose";
	public final static String COLOR_LAWN_GREEN = COLORURIBASE + ":lawn_green";
	public final static String COLOR_LEMON = COLORURIBASE + ":lemon";
	public final static String COLOR_LEMON_CHIFFON = COLORURIBASE + ":lemon_chiffon";
	public final static String COLOR_LIGHT_BLUE = COLORURIBASE + ":light_blue";
	public final static String COLOR_LIGHT_PINK = COLORURIBASE + ":light_pink";
	public final static String COLOR_LILAC = COLORURIBASE + ":lilac";
	public final static String COLOR_LIME_COLOR_WHEEL = COLORURIBASE + ":lime_color_wheel";
	public final static String COLOR_LIME_WEB_X11_GREEN = COLORURIBASE + ":lime_web_x11_green";
	public final static String COLOR_LIME_GREEN = COLORURIBASE + ":lime_green";
	public final static String COLOR_LINEN = COLORURIBASE + ":linen";
	public final static String COLOR_MAGENTA = COLORURIBASE + ":magenta";
	public final static String COLOR_MAGENTA_DYE = COLORURIBASE + ":magenta_dye";
	public final static String COLOR_MAGENTA_PROCESS = COLORURIBASE + ":magenta_process";
	public final static String COLOR_MAGIC_MINT = COLORURIBASE + ":magic_mint";
	public final static String COLOR_MAGNOLIA = COLORURIBASE + ":magnolia";
	public final static String COLOR_MALACHITE = COLORURIBASE + ":malachite";
	public final static String COLOR_MAROON_HTMLCSS = COLORURIBASE + ":maroon_html/css";
	public final static String COLOR_MAROON_X11 = COLORURIBASE + ":maroon_x11";
	public final static String COLOR_MAYA_BLUE = COLORURIBASE + ":maya_blue";
	public final static String COLOR_MAUVE = COLORURIBASE + ":mauve";
	public final static String COLOR_MAUVE_TAUPE = COLORURIBASE + ":mauve_taupe";
	public final static String COLOR_MEDIUM_BLUE = COLORURIBASE + ":medium_blue";
	public final static String COLOR_MEDIUM_CARMINE = COLORURIBASE + ":medium_carmine";
	public final static String COLOR_MEDIUM_LAVENDER_MAGENTA = COLORURIBASE + ":medium_lavender_magenta";
	public final static String COLOR_MEDIUM_PURPLE = COLORURIBASE + ":medium_purple";
	public final static String COLOR_MEDIUM_SPRING_GREEN = COLORURIBASE + ":medium_spring_green";
	public final static String COLOR_MIDNIGHT_BLUE = COLORURIBASE + ":midnight_blue";
	public final static String COLOR_MIDNIGHT_GREEN_EAGLE_GREEN = COLORURIBASE + ":midnight_green_eagle_green";
	public final static String COLOR_MINT_GREEN = COLORURIBASE + ":mint_green";
	public final static String COLOR_MISTY_ROSE = COLORURIBASE + ":misty_rose";
	public final static String COLOR_MOSS_GREEN = COLORURIBASE + ":moss_green";
	public final static String COLOR_MOUNTBATTEN_PINK = COLORURIBASE + ":mountbatten_pink";
	public final static String COLOR_MUSTARD = COLORURIBASE + ":mustard";
	public final static String COLOR_MYRTLE = COLORURIBASE + ":myrtle";
	public final static String COLOR_NAVAJO_WHITE = COLORURIBASE + ":navajo_white";
	public final static String COLOR_NAVY_BLUE = COLORURIBASE + ":navy_blue";
	public final static String COLOR_OCHRE = COLORURIBASE + ":ochre";
	public final static String COLOR_OFFICE_GREEN = COLORURIBASE + ":office_green";
	public final static String COLOR_OLD_GOLD = COLORURIBASE + ":old_gold";
	public final static String COLOR_OLD_LACE = COLORURIBASE + ":old_lace";
	public final static String COLOR_OLD_LAVENDER = COLORURIBASE + ":old_lavender";
	public final static String COLOR_OLD_ROSE = COLORURIBASE + ":old_rose";
	public final static String COLOR_OLIVE = COLORURIBASE + ":olive";
	public final static String COLOR_OLIVE_DRAB = COLORURIBASE + ":olive_drab";
	public final static String COLOR_OLIVINE = COLORURIBASE + ":olivine";
	public final static String COLOR_ORANGE_COLOR_WHEEL = COLORURIBASE + ":orange_color_wheel";
	public final static String COLOR_ORANGE_RYB = COLORURIBASE + ":orange_ryb";
	public final static String COLOR_ORANGE_WEB = COLORURIBASE + ":orange_web";
	public final static String COLOR_ORANGE_PEEL = COLORURIBASE + ":orange_peel";
	public final static String COLOR_ORANGE_RED = COLORURIBASE + ":orange-red";	    
	public final static String COLOR_ORCHID = COLORURIBASE + ":orchid";	    
	public final static String COLOR_PALE_BLUE = COLORURIBASE + ":pale_blue";	    
	public final static String COLOR_PALE_BROWN = COLORURIBASE + ":pale_brown";	    
	public final static String COLOR_PALE_CARMINE = COLORURIBASE + ":pale_carmine";	    
	public final static String COLOR_PALE_CHESTNUT = COLORURIBASE + ":pale_chestnut";	    
	public final static String COLOR_PALE_CORNFLOWER_BLUE = COLORURIBASE + ":pale_cornflower_blue";	    
	public final static String COLOR_PALE_MAGENTA = COLORURIBASE + ":pale_magenta";	    
	public final static String COLOR_PALE_PINK = COLORURIBASE + ":pale_pink";	    
	public final static String COLOR_PALE_RED_VIOLET = COLORURIBASE + ":pale_red-violet";	    
	public final static String COLOR_PAPAYA_WHIP = COLORURIBASE + ":papaya_whip";	    
	public final static String COLOR_PASTEL_GREEN = COLORURIBASE + ":pastel_green";	    
	public final static String COLOR_PASTEL_PINK = COLORURIBASE + ":pastel_pink";
	public final static String COLOR_PEACH = COLORURIBASE + ":peach";	    
	public final static String COLOR_PEACH_ORANGE = COLORURIBASE + ":peach-orange";	    
	public final static String COLOR_PEACH_YELLOW = COLORURIBASE + ":peach-yellow";	    
	public final static String COLOR_PEAR = COLORURIBASE + ":pear";	    
	public final static String COLOR_PERIWINKLE = COLORURIBASE + ":periwinkle";	    
	public final static String COLOR_PERSIAN_BLUE = COLORURIBASE + ":persian_blue";	    
	public final static String COLOR_PERSIAN_GREEN = COLORURIBASE + ":persian_green";	    
	public final static String COLOR_PERSIAN_INDIGO = COLORURIBASE + ":persian_indigo";	    
	public final static String COLOR_PERSIAN_ORANGE = COLORURIBASE + ":persian_orange";	    
	public final static String COLOR_PERSIAN_RED = COLORURIBASE + ":persian_red";	    
	public final static String COLOR_PERSIAN_PINK = COLORURIBASE + ":persian_pink";	    
	public final static String COLOR_PERSIAN_ROSE = COLORURIBASE + ":persian_rose";	    
	public final static String COLOR_PERSIMMON = COLORURIBASE + ":persimmon";	    
	public final static String COLOR_PINE_GREEN = COLORURIBASE + ":pine_green";	    
	public final static String COLOR_PINK = COLORURIBASE + ":pink";	    
	public final static String COLOR_PINK_ORANGE = COLORURIBASE + ":pink-orange";	    
	public final static String COLOR_PLATINUM = COLORURIBASE + ":platinum";	    
	public final static String COLOR_PLUM_WEB = COLORURIBASE + ":plum_web";	    
	public final static String COLOR_POWDER_BLUE_WEB = COLORURIBASE + ":powder_blue_web";	    
	public final static String COLOR_PUCE = COLORURIBASE + ":puce";	    
	public final static String COLOR_PRUSSIAN_BLUE = COLORURIBASE + ":prussian_blue";	    
	public final static String COLOR_PSYCHEDELIC_PURPLE = COLORURIBASE + ":psychedelic_purple";	    
	public final static String COLOR_PUMPKIN = COLORURIBASE + ":pumpkin";	    
	public final static String COLOR_PURPLE_HTMLCSS = COLORURIBASE + ":purple_html/css";	  	    
	public final static String COLOR_PURPLE_X11 = COLORURIBASE + ":purple_x11";	    
	public final static String COLOR_PURPLE_TAUPE = COLORURIBASE + ":purple_taupe";	    
	public final static String COLOR_RAW_UMBER = COLORURIBASE + ":raw_umber";	    
	public final static String COLOR_RAZZMATAZZ = COLORURIBASE + ":razzmatazz";	    
	public final static String COLOR_RED = COLORURIBASE + ":red";	    
	public final static String COLOR_RED_PIGMENT = COLORURIBASE + ":red_pigment";
	public final static String COLOR_RED_RYB = COLORURIBASE + ":red_ryb";	    
	public final static String COLOR_RED_VIOLET = COLORURIBASE + ":red-violet";	    
	public final static String COLOR_RICH_CARMINE = COLORURIBASE + ":rich_carmine";	    
	public final static String COLOR_ROBIN_EGG_BLUE = COLORURIBASE + ":robin_egg_blue";	    
	public final static String COLOR_ROSE = COLORURIBASE + ":rose";	    
	public final static String COLOR_ROSE_MADDER = COLORURIBASE + ":rose_madder";	    
	public final static String COLOR_ROSE_TAUPE = COLORURIBASE + ":rose_taupe";	    
	public final static String COLOR_ROYAL_BLUE = COLORURIBASE + ":royal_blue";
	public final static String COLOR_ROYAL_PURPLE = COLORURIBASE + ":royal_purple";
	public final static String COLOR_RUBY = COLORURIBASE + ":ruby";
	public final static String COLOR_RUSSET = COLORURIBASE + ":russet";	    
	public final static String COLOR_RUST = COLORURIBASE + ":rust";	    
	public final static String COLOR_SAFETY_ORANGE_BLAZE_ORANGE = COLORURIBASE + ":safety_orange_blaze_orange";	    
	public final static String COLOR_SAFFRON = COLORURIBASE + ":saffron";	    
	public final static String COLOR_SALMON = COLORURIBASE + ":salmon";	    
	public final static String COLOR_SANDY_BROWN = COLORURIBASE + ":sandy_brown";	    
	public final static String COLOR_SANGRIA = COLORURIBASE + ":sangria";	    
	public final static String COLOR_SAPPHIRE = COLORURIBASE + ":sapphire";	    
	public final static String COLOR_SCARLET = COLORURIBASE + ":scarlet";	    
	public final static String COLOR_SCHOOL_BUS_YELLOW = COLORURIBASE + ":school_bus_yellow";	    
	public final static String COLOR_SEA_GREEN = COLORURIBASE + ":sea_green";	    	  
	public final static String COLOR_SEASHELL = COLORURIBASE + ":seashell";	    
	public final static String COLOR_SELECTIVE_YELLOW = COLORURIBASE + ":selective_yellow";	    
	public final static String COLOR_SEPIA = COLORURIBASE + ":sepia";	    
	public final static String COLOR_SHAMROCK_GREEN = COLORURIBASE + ":shamrock_green";	    
	public final static String COLOR_SHOCKING_PINK = COLORURIBASE + ":shocking_pink";	    
	public final static String COLOR_SILVER = COLORURIBASE + ":silver";	    
	public final static String COLOR_SKY_BLUE = COLORURIBASE + ":sky_blue";	    
	public final static String COLOR_SLATE_GREY = COLORURIBASE + ":slate_grey";	    
	public final static String COLOR_SMALT_DARK_POWDER_BLUE = COLORURIBASE + ":smalt_dark_powder_blue";	    
	public final static String COLOR_SPRING_BUD = COLORURIBASE + ":spring_bud";	    
	public final static String COLOR_SPRING_GREEN = COLORURIBASE + ":spring_green";	    
	public final static String COLOR_STEEL_BLUE = COLORURIBASE + ":steel_blue";	    
	public final static String COLOR_TAN = COLORURIBASE + ":tan";	    
	public final static String COLOR_TANGERINE = COLORURIBASE + ":tangerine";	    
	public final static String COLOR_TANGERINE_YELLOW = COLORURIBASE + ":tangerine_yellow";	    
	public final static String COLOR_TAUPE = COLORURIBASE + ":taupe";	    
	public final static String COLOR_TEA_GREEN = COLORURIBASE + ":tea_green";	    
	public final static String COLOR_TEA_ROSE_ORANGE = COLORURIBASE + ":tea_rose_orange";	    
	public final static String COLOR_TEA_ROSE_ROSE = COLORURIBASE + ":tea_rose_rose";	    
	public final static String COLOR_TEAL = COLORURIBASE + ":teal";	    
	public final static String COLOR_TENNY_TAWNY = COLORURIBASE + ":tenny_tawny";	    
	public final static String COLOR_TERRA_COTTA = COLORURIBASE + ":terra_cotta";	    
	public final static String COLOR_THISTLE = COLORURIBASE + ":thistle";	    
	public final static String COLOR_TOMATO = COLORURIBASE + ":tomato";	    
	public final static String COLOR_TURQUOISE = COLORURIBASE + ":turquoise";	    
	public final static String COLOR_TYRIAN_PURPLE = COLORURIBASE + ":tyrian_purple";
	public final static String COLOR_ULTRAMARINE = COLORURIBASE + ":ultramarine";	    
	public final static String COLOR_ULTRA_PINK = COLORURIBASE + ":ultra_pink";	    
	public final static String COLOR_UNITED_NATIONS_BLUE = COLORURIBASE + ":united_nations_blue";	    
	public final static String COLOR_VEGAS_GOLD = COLORURIBASE + ":vegas_gold";	    
	public final static String COLOR_VERMILION = COLORURIBASE + ":vermilion";	    
	public final static String COLOR_VIOLET = COLORURIBASE + ":violet";	    
	public final static String COLOR_VIOLET_WEB = COLORURIBASE + ":violet_web";	    
	public final static String COLOR_VIOLET_RYB = COLORURIBASE + ":violet_ryb";	    
	public final static String COLOR_VIRIDIAN = COLORURIBASE + ":viridian";	    
	public final static String COLOR_WHEAT = COLORURIBASE + ":wheat";
	public final static String COLOR_WHITE = COLORURIBASE + ":white";	    
	public final static String COLOR_WISTERIA = COLORURIBASE + ":wisteria";
	public final static String COLOR_YELLOW = COLORURIBASE + ":yellow";
	public final static String COLOR_YELLOW_PROCESS = COLORURIBASE + ":yellow_process";
	public final static String COLOR_YELLOW_RYB = COLORURIBASE + ":yellow_ryb";
	public final static String COLOR_YELLOW_GREEN = COLORURIBASE + ":yellow-green";
	  	  
	static {
		colorTable_.put(COLOR_ALICE_BLUE, new Color( 240, 248, 255 ));
		colorTable_.put(COLOR_ALIZARIN, new Color( 227, 38, 54 ));
		colorTable_.put(COLOR_AMARANTH, new Color( 229, 43, 80 ));
		colorTable_.put(COLOR_AMARANTH_PINK, new Color( 241, 156, 187 ));
		colorTable_.put(COLOR_AMBER, new Color( 255, 191, 0 ));
		colorTable_.put(COLOR_AMETHYST, new Color( 153, 102, 204 ));
		colorTable_.put(COLOR_APRICOT, new Color( 251, 206, 177 ));
		colorTable_.put(COLOR_AQUA, new Color( 0, 255, 255 ));
		colorTable_.put(COLOR_AQUAMARINE, new Color( 127, 255, 212 ));
		colorTable_.put(COLOR_ARMY_GREEN, new Color( 75, 83, 32 ));
		colorTable_.put(COLOR_ASPARAGUS, new Color( 123, 160, 91 ));
		colorTable_.put(COLOR_ATOMIC_TANGERINE, new Color( 255, 153, 102 ));
		colorTable_.put(COLOR_AUBURN, new Color( 111, 53, 26 ));
		colorTable_.put(COLOR_AZURE_COLOR_WHEEL, new Color( 0, 127, 255 ));
		colorTable_.put(COLOR_AZURE_WEB, new Color( 0, 255, 255 ));
		colorTable_.put(COLOR_BABY_BLUE, new Color( 224, 255, 255 ));
		colorTable_.put(COLOR_BEIGE, new Color( 245, 245, 220 ));
		colorTable_.put(COLOR_BISTRE, new Color( 61, 43, 31 ));
		colorTable_.put(COLOR_BLACK, new Color( 0, 0, 0 ));
		colorTable_.put(COLOR_BLUE, new Color( 0, 0, 255 ));
		colorTable_.put(COLOR_BLUE_PIGMENT, new Color( 51, 51, 153 ));
		colorTable_.put(COLOR_BLUE_RYB, new Color( 2, 71, 254 ));
		colorTable_.put(COLOR_BLUE_GREEN, new Color( 0, 223, 223 ));
		colorTable_.put(COLOR_BLUE_VIOLET, new Color( 138, 43, 226 ));
		colorTable_.put(COLOR_BONDI_BLUE, new Color( 0, 149, 182 ));
		colorTable_.put(COLOR_BRASS, new Color( 181, 166, 66 ));
		colorTable_.put(COLOR_BRIGHT_GREEN, new Color( 102, 255, 0 ));
		colorTable_.put(COLOR_BRIGHT_PINK, new Color( 255, 0, 127 ));
		colorTable_.put(COLOR_BRIGHT_TURQUOISE, new Color( 8, 232, 222 ));
		colorTable_.put(COLOR_BRILLIANT_ROSE, new Color( 255, 85, 163 ));
		colorTable_.put(COLOR_BRINK_PINK, new Color( 251, 96, 127 ));
		colorTable_.put(COLOR_BRONZE, new Color( 205, 127, 50 ));
		colorTable_.put(COLOR_BROWN, new Color( 150, 75, 0 ));
		colorTable_.put(COLOR_BUFF, new Color( 240, 220, 130 ));
		colorTable_.put(COLOR_BURGUNDY, new Color( 128, 0, 32 ));
		colorTable_.put(COLOR_BURNT_ORANGE, new Color( 204, 85, 0 ));
		colorTable_.put(COLOR_BURNT_SIENNA, new Color( 233, 116, 81 ));
		colorTable_.put(COLOR_BURNT_UMBER, new Color( 138, 51, 36 ));
		colorTable_.put(COLOR_CAMOUFLAGE_GREEN, new Color( 120, 134, 107 ));
		colorTable_.put(COLOR_CAPUT_MORTUUM, new Color( 89, 39, 32 ));
		colorTable_.put(COLOR_CARDINAL, new Color( 196, 30, 58 ));
		colorTable_.put(COLOR_CARMINE, new Color( 150, 0, 24 ));
		colorTable_.put(COLOR_CARMINE_PINK, new Color( 235, 76, 66 ));
		colorTable_.put(COLOR_CARNATION_PINK, new Color( 255, 166, 201 ));
		colorTable_.put(COLOR_CAROLINA_BLUE, new Color( 156, 186, 227 ));
		colorTable_.put(COLOR_CARROT_ORANGE, new Color( 237, 145, 33 ));
		colorTable_.put(COLOR_CELADON, new Color( 172, 225, 175 ));
		colorTable_.put(COLOR_CERISE, new Color( 222, 49, 99 ));
		colorTable_.put(COLOR_CERISE_PINK, new Color( 236, 59, 131 ));
		colorTable_.put(COLOR_CERULEAN, new Color( 0, 123, 167 ));
		colorTable_.put(COLOR_CERULEAN_BLUE, new Color( 42, 82, 190 ));
		colorTable_.put(COLOR_CHAMPAGNE, new Color( 247, 231, 206 ));
		colorTable_.put(COLOR_CHARCOAL, new Color( 70, 70, 70 ));
		colorTable_.put(COLOR_CHARTREUSE_TRADITIONAL, new Color( 223, 255, 0 ));
		colorTable_.put(COLOR_CHARTREUSE_WEB, new Color( 127, 255, 0 ));
		colorTable_.put(COLOR_CHERRY_BLOSSOM_PINK, new Color( 255, 183, 197 ));
		colorTable_.put(COLOR_CHESTNUT, new Color( 205, 92, 92 ));
		colorTable_.put(COLOR_CHOCOLATE, new Color( 123, 63, 0 ));
		colorTable_.put(COLOR_CINNABAR, new Color( 227, 66, 52 ));
		colorTable_.put(COLOR_CINNAMON, new Color( 210, 105, 30 ));
		colorTable_.put(COLOR_COBALT, new Color( 0, 71, 171 ));
		colorTable_.put(COLOR_COLUMBIA_BLUE, new Color( 155, 221, 255 ));
		colorTable_.put(COLOR_COPPER, new Color( 184, 115, 51 ));
		colorTable_.put(COLOR_COPPER_ROSE, new Color( 153, 102, 102 ));
		colorTable_.put(COLOR_CORAL, new Color( 255, 127, 80 ));
		colorTable_.put(COLOR_CORAL_PINK, new Color( 248, 131, 121 ));
		colorTable_.put(COLOR_CORAL_RED, new Color( 255, 64, 64 ));
		colorTable_.put(COLOR_CORN, new Color( 251, 236, 93 ));
		colorTable_.put(COLOR_CORNFLOWER_BLUE, new Color( 100, 149, 237 ));
		colorTable_.put(COLOR_COSMIC_LATTE, new Color( 255, 248, 231 ));
		colorTable_.put(COLOR_CREAM, new Color( 255, 253, 208 ));
		colorTable_.put(COLOR_CRIMSON, new Color( 220, 20, 60 ));
		colorTable_.put(COLOR_CYAN, new Color( 0, 255, 255 ));
		colorTable_.put(COLOR_CYAN_PROCESS, new Color( 0, 180, 247 ));
		colorTable_.put(COLOR_DARK_BLUE, new Color( 0, 0, 139 ));
		colorTable_.put(COLOR_DARK_BROWN, new Color( 101, 67, 33 ));
		colorTable_.put(COLOR_DARK_CERULEAN, new Color( 8, 69, 126 ));
		colorTable_.put(COLOR_DARK_CHESTNUT, new Color( 152, 105, 96 ));
		colorTable_.put(COLOR_DARK_CORAL, new Color( 205, 91, 69 ));
		colorTable_.put(COLOR_DARK_GOLDENROD, new Color( 184, 134, 11 ));
		colorTable_.put(COLOR_DARK_GREEN, new Color( 1, 50, 32 ));
		colorTable_.put(COLOR_DARK_KHAKI, new Color( 189, 183, 107 ));
		colorTable_.put(COLOR_DARK_MAGENTA, new Color( 139, 0, 139 ));
		colorTable_.put(COLOR_DARK_PASTEL_GREEN, new Color( 3, 192, 60 ));
		colorTable_.put(COLOR_DARK_PINK, new Color( 231, 84, 128 ));
		colorTable_.put(COLOR_DARK_SCARLET, new Color( 86, 3, 25 ));
		colorTable_.put(COLOR_DARK_SALMON, new Color( 233, 150, 122 ));
		colorTable_.put(COLOR_DARK_SLATE_GRAY, new Color( 47, 79, 79 ));
		colorTable_.put(COLOR_DARK_SPRING_GREEN, new Color( 23, 114, 69 ));
		colorTable_.put(COLOR_DARK_TAN, new Color( 145, 129, 81 ));
		colorTable_.put(COLOR_DARK_TURQUOISE, new Color( 0, 206, 209 ));
		colorTable_.put(COLOR_DARK_VIOLET, new Color( 148, 0, 211 ));
		colorTable_.put(COLOR_DEEP_CARMINE_PINK, new Color( 239, 48, 56 ));
		colorTable_.put(COLOR_DEEP_CERISE, new Color( 218, 50, 135 ));
		colorTable_.put(COLOR_DEEP_CHESTNUT, new Color( 185, 78, 72 ));
		colorTable_.put(COLOR_DEEP_FUCHSIA, new Color( 193, 84, 193 ));
		colorTable_.put(COLOR_DEEP_LILAC, new Color( 153, 85, 187 ));
		colorTable_.put(COLOR_DEEP_MAGENTA, new Color( 204, 0, 204 ));
		colorTable_.put(COLOR_DEEP_PEACH, new Color( 255, 203, 164 ));
		colorTable_.put(COLOR_DEEP_PINK, new Color( 255, 20, 147 ));
		colorTable_.put(COLOR_DENIM, new Color( 21, 96, 189 ));
		colorTable_.put(COLOR_DODGER_BLUE, new Color( 30, 144, 255 ));
		colorTable_.put(COLOR_ECRU, new Color( 194, 178, 128 ));
		colorTable_.put(COLOR_EGYPTIAN_BLUE, new Color( 16, 52, 166 ));
		colorTable_.put(COLOR_ELECTRIC_BLUE, new Color( 125, 249, 255 ));
		colorTable_.put(COLOR_ELECTRIC_GREEN_X11_GREEN, new Color( 0, 255, 0 ));
		colorTable_.put(COLOR_ELECTRIC_INDIGO, new Color( 102, 0, 255 ));
		colorTable_.put(COLOR_ELECTRIC_LIME, new Color( 204, 255, 0 ));
		colorTable_.put(COLOR_ELECTRIC_PURPLE, new Color( 191, 0, 255 ));
		colorTable_.put(COLOR_EMERALD, new Color( 80, 200, 120 ));
		colorTable_.put(COLOR_EGGPLANT, new Color( 97, 64, 81 ));
		colorTable_.put(COLOR_FALU_RED, new Color( 128, 24, 24 ));
		colorTable_.put(COLOR_FERN_GREEN, new Color( 79, 121, 66 ));
		colorTable_.put(COLOR_FIREBRICK, new Color( 178, 34, 34 ));
		colorTable_.put(COLOR_FLAX, new Color( 238, 220, 130 ));
		colorTable_.put(COLOR_FOREST_GREEN, new Color( 34, 139, 34 ));
		colorTable_.put(COLOR_FRENCH_ROSE, new Color( 246, 74, 138 ));
		colorTable_.put(COLOR_FUCHSIA, new Color( 255, 0, 255 ));
		colorTable_.put(COLOR_FUCHSIA_PINK, new Color( 255, 119, 255 ));
		colorTable_.put(COLOR_GAMBOGE, new Color( 228, 155, 15 ));
		colorTable_.put(COLOR_GOLD_METALLIC, new Color( 212, 175, 55 ));
		colorTable_.put(COLOR_GOLD_WEB_GOLDEN, new Color( 255, 215, 0 ));
		colorTable_.put(COLOR_GOLDEN_BROWN, new Color( 153, 101, 21 ));
		colorTable_.put(COLOR_GOLDEN_YELLOW, new Color( 255, 223, 0 ));
		colorTable_.put(COLOR_GOLDENROD, new Color( 218, 165, 32 ));
		colorTable_.put(COLOR_GREY_ASPARAGUS, new Color( 70, 89, 69 ));
		colorTable_.put(COLOR_GREEN_COLOR_WHEEL_X11_GREEN, new Color( 0, 255, 0 ));
		colorTable_.put(COLOR_GREEN_HTMLCSS_GREEN, new Color( 0, 128, 0 ));
		colorTable_.put(COLOR_GREEN_PIGMENT, new Color( 0, 165, 80 ));
		colorTable_.put(COLOR_GREEN_RYB, new Color( 102, 176, 50 ));
		colorTable_.put(COLOR_GREEN_YELLOW, new Color( 173, 255, 47 ));
		colorTable_.put(COLOR_GREY, new Color( 128, 128, 128 ));
		colorTable_.put(COLOR_HAN_PURPLE, new Color( 82, 24, 250 ));
		colorTable_.put(COLOR_HARLEQUIN, new Color( 63, 255, 0 ));
		colorTable_.put(COLOR_HELIOTROPE, new Color( 223, 115, 255 ));
		colorTable_.put(COLOR_HOLLYWOOD_CERISE, new Color( 244, 0, 161 ));
		colorTable_.put(COLOR_HOT_MAGENTA, new Color( 255, 0, 204 ));
		colorTable_.put(COLOR_HOT_PINK, new Color( 255, 105, 180 ));
		colorTable_.put(COLOR_INDIGO_DYE, new Color( 0, 65, 106 ));
		colorTable_.put(COLOR_INDIGO_WEB, new Color( 75, 0, 130 ));
		colorTable_.put(COLOR_INTERNATIONAL_KLEIN_BLUE, new Color( 0, 47, 167 ));
		colorTable_.put(COLOR_INTERNATIONAL_ORANGE, new Color( 255, 79, 0 ));
		colorTable_.put(COLOR_ISLAMIC_GREEN, new Color( 0, 153, 0 ));
		colorTable_.put(COLOR_IVORY, new Color( 255, 255, 240 ));
		colorTable_.put(COLOR_JADE, new Color( 0, 168, 107 ));
		colorTable_.put(COLOR_KELLY_GREEN, new Color( 76, 187, 23 ));
		colorTable_.put(COLOR_KHAKI, new Color( 195, 176, 145 ));
		colorTable_.put(COLOR_KHAKI_X11_LIGHT_KHAKI, new Color( 240, 230, 140 ));
		colorTable_.put(COLOR_LAVENDER_FLORAL, new Color( 181, 126, 220 ));
		colorTable_.put(COLOR_LAVENDER_WEB, new Color( 230, 230, 250 ));
		colorTable_.put(COLOR_LAVENDER_BLUE, new Color( 204, 204, 255 ));
		colorTable_.put(COLOR_LAVENDER_BLUSH, new Color( 255, 240, 245 ));
		colorTable_.put(COLOR_LAVENDER_GREY, new Color( 196, 195, 221 ));
		colorTable_.put(COLOR_LAVENDER_MAGENTA, new Color( 238, 130, 238 ));
		colorTable_.put(COLOR_LAVENDER_PINK, new Color( 251, 174, 210 ));
		colorTable_.put(COLOR_LAVENDER_PURPLE, new Color( 150, 120, 182 ));
		colorTable_.put(COLOR_LAVENDER_ROSE, new Color( 251, 160, 227 ));
		colorTable_.put(COLOR_LAWN_GREEN, new Color( 124, 252, 0 ));
		colorTable_.put(COLOR_LEMON, new Color( 253, 233, 16 ));
		colorTable_.put(COLOR_LEMON_CHIFFON, new Color( 255, 250, 205 ));
		colorTable_.put(COLOR_LIGHT_BLUE, new Color( 173, 216, 230 ));
		colorTable_.put(COLOR_LIGHT_PINK, new Color( 255, 182, 193 ));
		colorTable_.put(COLOR_LILAC, new Color( 200, 162, 200 ));
		colorTable_.put(COLOR_LIME_COLOR_WHEEL, new Color( 191, 255, 0 ));
		colorTable_.put(COLOR_LIME_WEB_X11_GREEN, new Color( 0, 255, 0 ));
		colorTable_.put(COLOR_LIME_GREEN, new Color( 50, 205, 50 ));
		colorTable_.put(COLOR_LINEN, new Color( 250, 240, 230 ));
		colorTable_.put(COLOR_MAGENTA, new Color( 255, 0, 255 ));
		colorTable_.put(COLOR_MAGENTA_DYE, new Color( 202, 31, 23 ));
		colorTable_.put(COLOR_MAGENTA_PROCESS, new Color( 255, 0, 144 ));
		colorTable_.put(COLOR_MAGIC_MINT, new Color( 170, 240, 209 ));
		colorTable_.put(COLOR_MAGNOLIA, new Color( 248, 244, 255 ));
		colorTable_.put(COLOR_MALACHITE, new Color( 11, 218, 81 ));
		colorTable_.put(COLOR_MAROON_HTMLCSS, new Color( 128, 0, 0 ));
		colorTable_.put(COLOR_MAROON_X11, new Color( 176, 48, 96 ));
		colorTable_.put(COLOR_MAYA_BLUE, new Color( 115, 194, 251 ));
		colorTable_.put(COLOR_MAUVE, new Color( 224, 176, 255 ));
		colorTable_.put(COLOR_MAUVE_TAUPE, new Color( 145, 95, 109 ));
		colorTable_.put(COLOR_MEDIUM_BLUE, new Color( 0, 0, 205 ));
		colorTable_.put(COLOR_MEDIUM_CARMINE, new Color( 175, 64, 53 ));
		colorTable_.put(COLOR_MEDIUM_LAVENDER_MAGENTA, new Color( 204, 153, 204 ));
		colorTable_.put(COLOR_MEDIUM_PURPLE, new Color( 147, 112, 219 ));
		colorTable_.put(COLOR_MEDIUM_SPRING_GREEN, new Color( 0, 250, 154 ));
		colorTable_.put(COLOR_MIDNIGHT_BLUE, new Color( 25, 25, 112 ));
		colorTable_.put(COLOR_MIDNIGHT_GREEN_EAGLE_GREEN, new Color( 0, 73, 83 ));
		colorTable_.put(COLOR_MINT_GREEN, new Color( 152, 255, 152 ));
		colorTable_.put(COLOR_MISTY_ROSE, new Color( 255, 228, 225 ));
		colorTable_.put(COLOR_MOSS_GREEN, new Color( 173, 223, 173 ));
		colorTable_.put(COLOR_MOUNTBATTEN_PINK, new Color( 153, 122, 141 ));
		colorTable_.put(COLOR_MUSTARD, new Color( 255, 219, 88 ));
		colorTable_.put(COLOR_MYRTLE, new Color( 33, 66, 30 ));
		colorTable_.put(COLOR_NAVAJO_WHITE, new Color( 255, 222, 173 ));
		colorTable_.put(COLOR_NAVY_BLUE, new Color( 0, 0, 128 ));
		colorTable_.put(COLOR_OCHRE, new Color( 204, 119, 34 ));
		colorTable_.put(COLOR_OFFICE_GREEN, new Color( 0, 128, 0 ));
		colorTable_.put(COLOR_OLD_GOLD, new Color( 207, 181, 59 ));
		colorTable_.put(COLOR_OLD_LACE, new Color( 253, 245, 230 ));
		colorTable_.put(COLOR_OLD_LAVENDER, new Color( 121, 104, 120 ));
		colorTable_.put(COLOR_OLD_ROSE, new Color( 192, 128, 129 ));
		colorTable_.put(COLOR_OLIVE, new Color( 128, 128, 0 ));
		colorTable_.put(COLOR_OLIVE_DRAB, new Color( 107, 142, 35 ));
		colorTable_.put(COLOR_OLIVINE, new Color( 154, 185, 115 ));
		colorTable_.put(COLOR_ORANGE_COLOR_WHEEL, new Color( 255, 127, 0 ));
		colorTable_.put(COLOR_ORANGE_RYB, new Color( 251, 153, 2 ));
		colorTable_.put(COLOR_ORANGE_WEB, new Color( 255, 165, 0 ));
		colorTable_.put(COLOR_ORANGE_PEEL, new Color( 255, 160, 0 ));	  
		colorTable_.put(COLOR_ORANGE_RED, new Color( 255, 69, 0 ));	  
		colorTable_.put(COLOR_ORCHID, new Color( 218, 112, 214 ));	  	  
		colorTable_.put(COLOR_PALE_BLUE, new Color( 175, 238, 238 ));	  
		colorTable_.put(COLOR_PALE_BROWN, new Color( 152, 118, 84 ));	  
		colorTable_.put(COLOR_PALE_CARMINE, new Color( 175, 64, 53 ));	  
		colorTable_.put(COLOR_PALE_CHESTNUT, new Color( 221, 173, 175 ));	  
		colorTable_.put(COLOR_PALE_CORNFLOWER_BLUE, new Color( 171, 205, 239 ));	  
		colorTable_.put(COLOR_PALE_MAGENTA, new Color( 249, 132, 229 ));	  
		colorTable_.put(COLOR_PALE_PINK, new Color( 250, 218, 221 ));	  
		colorTable_.put(COLOR_PALE_RED_VIOLET, new Color( 219, 112, 147 ));	  
		colorTable_.put(COLOR_PAPAYA_WHIP, new Color( 255, 239, 213 ));	  
		colorTable_.put(COLOR_PASTEL_GREEN, new Color( 119, 221, 119 ));	  
		colorTable_.put(COLOR_PASTEL_PINK, new Color( 255, 209, 220 ));	  
		colorTable_.put(COLOR_PEACH, new Color( 255, 229, 180 ));	  
		colorTable_.put(COLOR_PEACH_ORANGE, new Color( 255, 204, 153 ));	  
		colorTable_.put(COLOR_PEACH_YELLOW, new Color( 250, 223, 173 ));	  
		colorTable_.put(COLOR_PEAR, new Color( 209, 226, 49 ));	  
		colorTable_.put(COLOR_PERIWINKLE, new Color( 204, 204, 255 ));	  
		colorTable_.put(COLOR_PERSIAN_BLUE, new Color( 28, 57, 187 ));	  
		colorTable_.put(COLOR_PERSIAN_GREEN, new Color( 0, 166, 147 ));	  
		colorTable_.put(COLOR_PERSIAN_INDIGO, new Color( 50, 18, 122 ));	  
		colorTable_.put(COLOR_PERSIAN_ORANGE, new Color( 217, 144, 88 ));	  
		colorTable_.put(COLOR_PERSIAN_RED, new Color( 204, 51, 51 ));	  
		colorTable_.put(COLOR_PERSIAN_PINK, new Color( 247, 127, 190 ));	  
		colorTable_.put(COLOR_PERSIAN_ROSE, new Color( 254, 40, 162 ));	  
		colorTable_.put(COLOR_PERSIMMON, new Color( 236, 88, 0 ));	  
		colorTable_.put(COLOR_PINE_GREEN, new Color( 1, 121, 111 ));	  
		colorTable_.put(COLOR_PINK, new Color( 255, 192, 203 ));	  
		colorTable_.put(COLOR_PINK_ORANGE, new Color( 255, 153, 102 ));	  
		colorTable_.put(COLOR_PLATINUM, new Color( 229, 228, 226 ));	  
		colorTable_.put(COLOR_PLUM_WEB, new Color( 204, 153, 204 ));	  
		colorTable_.put(COLOR_POWDER_BLUE_WEB, new Color( 176, 224, 230 ));	  
		colorTable_.put(COLOR_PUCE, new Color( 204, 136, 153 ));	  
		colorTable_.put(COLOR_PRUSSIAN_BLUE, new Color( 0, 49, 83 ));	  
		colorTable_.put(COLOR_PSYCHEDELIC_PURPLE, new Color( 221, 0, 255 ));	  
		colorTable_.put(COLOR_PUMPKIN, new Color( 255, 117, 24 ));	  
		colorTable_.put(COLOR_PURPLE_HTMLCSS, new Color( 128, 0, 128 ));	  
		colorTable_.put(COLOR_PURPLE_X11, new Color( 160, 92, 240 ));	  
		colorTable_.put(COLOR_PURPLE_TAUPE, new Color( 80, 64, 77 ));	  
		colorTable_.put(COLOR_RAW_UMBER, new Color( 115, 74, 18 ));	  
		colorTable_.put(COLOR_RAZZMATAZZ, new Color( 227, 11, 92 ));	  
		colorTable_.put(COLOR_RED, new Color( 255, 0, 0 ));	  
		colorTable_.put(COLOR_RED_PIGMENT, new Color( 237, 28, 36 ));	  
		colorTable_.put(COLOR_RED_RYB, new Color( 254, 39, 18 ));	  
		colorTable_.put(COLOR_RED_VIOLET, new Color( 199, 21, 133 ));	  
		colorTable_.put(COLOR_RICH_CARMINE, new Color( 215, 0, 64 ));	  
		colorTable_.put(COLOR_ROBIN_EGG_BLUE, new Color( 0, 204, 204 ));	  
		colorTable_.put(COLOR_ROSE, new Color( 255, 0, 127 ));	  
		colorTable_.put(COLOR_ROSE_MADDER, new Color( 227, 38, 54 ));	  
		colorTable_.put(COLOR_ROSE_TAUPE, new Color( 144, 93, 93 ));	  
		colorTable_.put(COLOR_ROYAL_BLUE, new Color( 65, 105, 225 ));
		colorTable_.put(COLOR_ROYAL_PURPLE, new Color( 107, 63, 160 ));
		colorTable_.put(COLOR_RUBY, new Color( 224, 17, 95 ));
		colorTable_.put(COLOR_RUSSET, new Color( 128, 70, 27 ));	  
		colorTable_.put(COLOR_RUST, new Color( 183, 65, 14 ));	  
		colorTable_.put(COLOR_SAFETY_ORANGE_BLAZE_ORANGE, new Color( 255, 102, 0 ));	  
		colorTable_.put(COLOR_SAFFRON, new Color( 244, 196, 48 ));	  
		colorTable_.put(COLOR_SALMON, new Color( 255, 140, 105 ));	  
		colorTable_.put(COLOR_SANDY_BROWN, new Color( 244, 164, 96 ));	  
		colorTable_.put(COLOR_SANGRIA, new Color( 146, 0, 10 ));	  
		colorTable_.put(COLOR_SAPPHIRE, new Color( 8, 37, 103 ));	  
		colorTable_.put(COLOR_SCARLET, new Color( 255, 36, 0 ));	  
		colorTable_.put(COLOR_SCHOOL_BUS_YELLOW, new Color( 255, 216, 0 ));	  
		colorTable_.put(COLOR_SEA_GREEN, new Color( 46, 139, 87 ));	  
		colorTable_.put(COLOR_SEASHELL, new Color( 255, 245, 238 ));	  
		colorTable_.put(COLOR_SELECTIVE_YELLOW, new Color( 255, 186, 0 ));	  
		colorTable_.put(COLOR_SEPIA, new Color( 112, 66, 20 ));	  
		colorTable_.put(COLOR_SHAMROCK_GREEN, new Color( 0, 158, 96 ));	  
		colorTable_.put(COLOR_SHOCKING_PINK, new Color( 252, 15, 192 ));	  
		colorTable_.put(COLOR_SILVER, new Color( 192, 192, 192 ));	  
		colorTable_.put(COLOR_SKY_BLUE, new Color( 135, 206, 235 ));	  
		colorTable_.put(COLOR_SLATE_GREY, new Color( 112, 128, 144 ));	  
		colorTable_.put(COLOR_SMALT_DARK_POWDER_BLUE, new Color( 0, 51, 153 ));	  
		colorTable_.put(COLOR_SPRING_BUD, new Color( 167, 252, 0 ));	  
		colorTable_.put(COLOR_SPRING_GREEN, new Color( 0, 255, 127 ));	  
		colorTable_.put(COLOR_STEEL_BLUE, new Color( 70, 130, 180 ));	  
		colorTable_.put(COLOR_TAN, new Color( 210, 180, 140 ));	  
		colorTable_.put(COLOR_TANGERINE, new Color( 242, 133, 0 ));	  
		colorTable_.put(COLOR_TANGERINE_YELLOW, new Color( 255, 204, 0 ));	  
		colorTable_.put(COLOR_TAUPE, new Color( 72, 60, 50 ));	  
		colorTable_.put(COLOR_TEA_GREEN, new Color( 208, 240, 192 ));	  
		colorTable_.put(COLOR_TEA_ROSE_ORANGE, new Color( 248, 131, 194 ));	  
		colorTable_.put(COLOR_TEA_ROSE_ROSE, new Color( 244, 194, 194 ));	  
		colorTable_.put(COLOR_TEAL, new Color( 0, 128, 128 ));	  
		colorTable_.put(COLOR_TENNY_TAWNY, new Color( 205, 87, 0 ));	  
		colorTable_.put(COLOR_TERRA_COTTA, new Color( 226, 114, 91 ));	  
		colorTable_.put(COLOR_THISTLE, new Color( 216, 191, 216 ));	  
		colorTable_.put(COLOR_TOMATO, new Color( 255, 99, 71 ));	  
		colorTable_.put(COLOR_TURQUOISE, new Color( 48, 213, 200 ));	  
		colorTable_.put(COLOR_TYRIAN_PURPLE, new Color( 102, 2, 60 ));	  
		colorTable_.put(COLOR_ULTRAMARINE, new Color( 18 , 10 , 143 ));	  
		colorTable_.put(COLOR_ULTRA_PINK, new Color( 255, 111, 255 ));	  
		colorTable_.put(COLOR_UNITED_NATIONS_BLUE, new Color( 91, 146, 229 ));	  
		colorTable_.put(COLOR_VEGAS_GOLD, new Color( 197, 179, 88 ));	  
		colorTable_.put(COLOR_VERMILION, new Color( 227, 66, 51 ));	  
		colorTable_.put(COLOR_VIOLET, new Color( 139, 0, 255 ));	  
		colorTable_.put(COLOR_VIOLET_WEB, new Color( 238, 130, 238 ));	  
		colorTable_.put(COLOR_VIOLET_RYB, new Color( 2, 71, 54 ));	  
		colorTable_.put(COLOR_VIRIDIAN, new Color( 64, 130, 109 ));	  
		colorTable_.put(COLOR_WHEAT, new Color( 245, 222, 179 ));
		colorTable_.put(COLOR_WHITE, new Color( 255, 255, 255 ));
		colorTable_.put(COLOR_WISTERIA, new Color( 201, 160, 220 ));
		colorTable_.put(COLOR_YELLOW, new Color( 255, 255, 0 ));
		colorTable_.put(COLOR_YELLOW_PROCESS, new Color( 255, 239, 0 ));
		colorTable_.put(COLOR_YELLOW_RYB, new Color( 254, 254, 51 ));
		colorTable_.put(COLOR_YELLOW_GREEN, new Color( 154, 205, 50 ));
	}
	
	public static Hashtable<String, Color> getColorTable() {
		return colorTable_;
	}
	
	public static boolean containsColor(String colorURI) {
		return colorTable_.containsKey(colorURI);
	}
	
	public static Color getRGBforColor(String colorURI) {
		return colorTable_.get(colorURI);
	}

	// A.2.2	LocationCS
	private static Vector<String> locationTable_ = new Vector<String>();
	
	public final static String LOCATIONURIBASE = "urn:mpeg:mpeg-v:01-SI-LocationCS-NS";
	public final static String LOC_X_LEFT = ":left";
	public final static String LOC_X_CENTERLEFT = ":centerleft";
	public final static String LOC_X_CENTER = ":center";
	public final static String LOC_X_CENTERRIGHT = ":centerright";
	public final static String LOC_X_RIGHT = ":right";
	public final static String LOC_Y_BOTTOM = ":bottom";
	public final static String LOC_Y_MIDDLE = ":middle";
	public final static String LOC_Y_TOP = ":top";
	public final static String LOC_Z_BACK = ":back";
	public final static String LOC_Z_MIDWAY = ":midway";
	public final static String LOC_Z_FRONT = ":front";
	public final static String LOC_EVERYWHERE = ":*";
	
	static {
		// x left
		locationTable_.add(LOCATIONURIBASE + LOC_X_LEFT + LOC_Y_BOTTOM + LOC_Z_BACK);
		locationTable_.add(LOCATIONURIBASE + LOC_X_LEFT + LOC_Y_BOTTOM + LOC_Z_MIDWAY);
		locationTable_.add(LOCATIONURIBASE + LOC_X_LEFT + LOC_Y_BOTTOM + LOC_Z_FRONT);
		locationTable_.add(LOCATIONURIBASE + LOC_X_LEFT + LOC_Y_MIDDLE + LOC_Z_BACK);
		locationTable_.add(LOCATIONURIBASE + LOC_X_LEFT + LOC_Y_MIDDLE + LOC_Z_MIDWAY);
		locationTable_.add(LOCATIONURIBASE + LOC_X_LEFT + LOC_Y_MIDDLE + LOC_Z_FRONT);
		locationTable_.add(LOCATIONURIBASE + LOC_X_LEFT + LOC_Y_TOP + LOC_Z_BACK);
		locationTable_.add(LOCATIONURIBASE + LOC_X_LEFT + LOC_Y_TOP + LOC_Z_MIDWAY);
		locationTable_.add(LOCATIONURIBASE + LOC_X_LEFT + LOC_Y_TOP + LOC_Z_FRONT);
		locationTable_.add(LOCATIONURIBASE + LOC_X_LEFT + LOC_EVERYWHERE + LOC_Z_BACK);
		locationTable_.add(LOCATIONURIBASE + LOC_X_LEFT + LOC_EVERYWHERE + LOC_Z_MIDWAY);
		locationTable_.add(LOCATIONURIBASE + LOC_X_LEFT + LOC_EVERYWHERE + LOC_Z_FRONT);
		locationTable_.add(LOCATIONURIBASE + LOC_X_LEFT + LOC_Y_BOTTOM + LOC_EVERYWHERE);
		locationTable_.add(LOCATIONURIBASE + LOC_X_LEFT + LOC_Y_MIDDLE + LOC_EVERYWHERE);
		locationTable_.add(LOCATIONURIBASE + LOC_X_LEFT + LOC_Y_TOP + LOC_EVERYWHERE);
		locationTable_.add(LOCATIONURIBASE + LOC_X_LEFT + LOC_EVERYWHERE + LOC_EVERYWHERE);
		
		// x centerleft
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTERLEFT + LOC_Y_BOTTOM + LOC_Z_BACK);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTERLEFT + LOC_Y_BOTTOM + LOC_Z_MIDWAY);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTERLEFT + LOC_Y_BOTTOM + LOC_Z_FRONT);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTERLEFT + LOC_Y_MIDDLE + LOC_Z_BACK);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTERLEFT + LOC_Y_MIDDLE + LOC_Z_MIDWAY);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTERLEFT + LOC_Y_MIDDLE + LOC_Z_FRONT);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTERLEFT + LOC_Y_TOP + LOC_Z_BACK);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTERLEFT + LOC_Y_TOP + LOC_Z_MIDWAY);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTERLEFT + LOC_Y_TOP + LOC_Z_FRONT);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTERLEFT + LOC_EVERYWHERE + LOC_Z_BACK);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTERLEFT + LOC_EVERYWHERE + LOC_Z_MIDWAY);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTERLEFT + LOC_EVERYWHERE + LOC_Z_FRONT);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTERLEFT + LOC_Y_BOTTOM + LOC_EVERYWHERE);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTERLEFT + LOC_Y_MIDDLE + LOC_EVERYWHERE);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTERLEFT + LOC_Y_TOP + LOC_EVERYWHERE);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTERLEFT + LOC_EVERYWHERE + LOC_EVERYWHERE);

		// x center
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTER + LOC_Y_BOTTOM + LOC_Z_BACK);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTER + LOC_Y_BOTTOM + LOC_Z_MIDWAY);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTER + LOC_Y_BOTTOM + LOC_Z_FRONT);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTER + LOC_Y_MIDDLE + LOC_Z_BACK);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTER + LOC_Y_MIDDLE + LOC_Z_MIDWAY);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTER + LOC_Y_MIDDLE + LOC_Z_FRONT);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTER + LOC_Y_TOP + LOC_Z_BACK);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTER + LOC_Y_TOP + LOC_Z_MIDWAY);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTER + LOC_Y_TOP + LOC_Z_FRONT);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTER + LOC_EVERYWHERE + LOC_Z_BACK);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTER + LOC_EVERYWHERE + LOC_Z_MIDWAY);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTER + LOC_EVERYWHERE + LOC_Z_FRONT);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTER + LOC_Y_BOTTOM + LOC_EVERYWHERE);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTER + LOC_Y_MIDDLE + LOC_EVERYWHERE);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTER + LOC_Y_TOP + LOC_EVERYWHERE);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTER + LOC_EVERYWHERE + LOC_EVERYWHERE);
		
		// x centerright
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTERRIGHT + LOC_Y_BOTTOM + LOC_Z_BACK);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTERRIGHT + LOC_Y_BOTTOM + LOC_Z_MIDWAY);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTERRIGHT + LOC_Y_BOTTOM + LOC_Z_FRONT);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTERRIGHT + LOC_Y_MIDDLE + LOC_Z_BACK);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTERRIGHT + LOC_Y_MIDDLE + LOC_Z_MIDWAY);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTERRIGHT + LOC_Y_MIDDLE + LOC_Z_FRONT);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTERRIGHT + LOC_Y_TOP + LOC_Z_BACK);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTERRIGHT + LOC_Y_TOP + LOC_Z_MIDWAY);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTERRIGHT + LOC_Y_TOP + LOC_Z_FRONT);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTERRIGHT + LOC_EVERYWHERE + LOC_Z_BACK);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTERRIGHT + LOC_EVERYWHERE + LOC_Z_MIDWAY);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTERRIGHT + LOC_EVERYWHERE + LOC_Z_FRONT);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTERRIGHT + LOC_Y_BOTTOM + LOC_EVERYWHERE);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTERRIGHT + LOC_Y_MIDDLE + LOC_EVERYWHERE);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTERRIGHT + LOC_Y_TOP + LOC_EVERYWHERE);
		locationTable_.add(LOCATIONURIBASE + LOC_X_CENTERRIGHT + LOC_EVERYWHERE + LOC_EVERYWHERE);
		
		// x right
		locationTable_.add(LOCATIONURIBASE + LOC_X_RIGHT + LOC_Y_BOTTOM + LOC_Z_BACK);
		locationTable_.add(LOCATIONURIBASE + LOC_X_RIGHT + LOC_Y_BOTTOM + LOC_Z_MIDWAY);
		locationTable_.add(LOCATIONURIBASE + LOC_X_RIGHT + LOC_Y_BOTTOM + LOC_Z_FRONT);
		locationTable_.add(LOCATIONURIBASE + LOC_X_RIGHT + LOC_Y_MIDDLE + LOC_Z_BACK);
		locationTable_.add(LOCATIONURIBASE + LOC_X_RIGHT + LOC_Y_MIDDLE + LOC_Z_MIDWAY);
		locationTable_.add(LOCATIONURIBASE + LOC_X_RIGHT + LOC_Y_MIDDLE + LOC_Z_FRONT);
		locationTable_.add(LOCATIONURIBASE + LOC_X_RIGHT + LOC_Y_TOP + LOC_Z_BACK);
		locationTable_.add(LOCATIONURIBASE + LOC_X_RIGHT + LOC_Y_TOP + LOC_Z_MIDWAY);
		locationTable_.add(LOCATIONURIBASE + LOC_X_RIGHT + LOC_Y_TOP + LOC_Z_FRONT);
		locationTable_.add(LOCATIONURIBASE + LOC_X_RIGHT + LOC_EVERYWHERE + LOC_Z_BACK);
		locationTable_.add(LOCATIONURIBASE + LOC_X_RIGHT + LOC_EVERYWHERE + LOC_Z_MIDWAY);
		locationTable_.add(LOCATIONURIBASE + LOC_X_RIGHT + LOC_EVERYWHERE + LOC_Z_FRONT);
		locationTable_.add(LOCATIONURIBASE + LOC_X_RIGHT + LOC_Y_BOTTOM + LOC_EVERYWHERE);
		locationTable_.add(LOCATIONURIBASE + LOC_X_RIGHT + LOC_Y_MIDDLE + LOC_EVERYWHERE);
		locationTable_.add(LOCATIONURIBASE + LOC_X_RIGHT + LOC_Y_TOP + LOC_EVERYWHERE);
		locationTable_.add(LOCATIONURIBASE + LOC_X_RIGHT + LOC_EVERYWHERE + LOC_EVERYWHERE);
		
		// x everywhere
		locationTable_.add(LOCATIONURIBASE + LOC_EVERYWHERE + LOC_Y_BOTTOM + LOC_Z_BACK);
		locationTable_.add(LOCATIONURIBASE + LOC_EVERYWHERE + LOC_Y_BOTTOM + LOC_Z_MIDWAY);
		locationTable_.add(LOCATIONURIBASE + LOC_EVERYWHERE + LOC_Y_BOTTOM + LOC_Z_FRONT);
		locationTable_.add(LOCATIONURIBASE + LOC_EVERYWHERE + LOC_Y_MIDDLE + LOC_Z_BACK);
		locationTable_.add(LOCATIONURIBASE + LOC_EVERYWHERE + LOC_Y_MIDDLE + LOC_Z_MIDWAY);
		locationTable_.add(LOCATIONURIBASE + LOC_EVERYWHERE + LOC_Y_MIDDLE + LOC_Z_FRONT);
		locationTable_.add(LOCATIONURIBASE + LOC_EVERYWHERE + LOC_Y_TOP + LOC_Z_BACK);
		locationTable_.add(LOCATIONURIBASE + LOC_EVERYWHERE + LOC_Y_TOP + LOC_Z_MIDWAY);
		locationTable_.add(LOCATIONURIBASE + LOC_EVERYWHERE + LOC_Y_TOP + LOC_Z_FRONT);
		locationTable_.add(LOCATIONURIBASE + LOC_EVERYWHERE + LOC_EVERYWHERE + LOC_Z_BACK);
		locationTable_.add(LOCATIONURIBASE + LOC_EVERYWHERE + LOC_EVERYWHERE + LOC_Z_MIDWAY);
		locationTable_.add(LOCATIONURIBASE + LOC_EVERYWHERE + LOC_EVERYWHERE + LOC_Z_FRONT);
		locationTable_.add(LOCATIONURIBASE + LOC_EVERYWHERE + LOC_Y_BOTTOM + LOC_EVERYWHERE);
		locationTable_.add(LOCATIONURIBASE + LOC_EVERYWHERE + LOC_Y_MIDDLE + LOC_EVERYWHERE);
		locationTable_.add(LOCATIONURIBASE + LOC_EVERYWHERE + LOC_Y_TOP + LOC_EVERYWHERE);
		locationTable_.add(LOCATIONURIBASE + LOC_EVERYWHERE + LOC_EVERYWHERE + LOC_EVERYWHERE);
	}
	
	public static Vector<String> getLocationTable() {
		return locationTable_;
	}
	
	public static boolean containsLocation(String locationURI) {
		return locationTable_.contains(locationURI);
	}

	// A.2.3	ScentCS
	private static Vector<String> scentTable_ =  new Vector<String>();
	public final static String SCENTURIBASE = "urn:mpeg:mpeg-v:01-SI-ScentCS-NS";
	public final static String SCENT_ROSE = SCENTURIBASE + ":rose";
	public final static String SCENT_ACACIA = SCENTURIBASE + ":acacia";
	public final static String SCENT_CHRYSANTHEMUM = SCENTURIBASE + ":chrysanthemum";
	public final static String SCENT_LILAC = SCENTURIBASE + ":lilac";
	public final static String SCENT_MINT = SCENTURIBASE + ":mint";
	public final static String SCENT_JASMINE = SCENTURIBASE + ":jasmine";
	public final static String SCENT_PINE_TREE = SCENTURIBASE + ":pine_tree";
	public final static String SCENT_ORANGE = SCENTURIBASE + ":orange";
	public final static String SCENT_GRAPE = SCENTURIBASE + ":grape";
	public final static String SCENT_ALMONDS = SCENTURIBASE + ":almonds";
	public final static String SCENT_AMARETTO = SCENTURIBASE + ":amaretto";
	public final static String SCENT_APPLES_GREEN = SCENTURIBASE + ":apples_green";
	public final static String SCENT_APPLES_RED = SCENTURIBASE + ":apples_red";
	public final static String SCENT_BACON = SCENTURIBASE + ":bacon";
	public final static String SCENT_BACON_SMOKEY = SCENTURIBASE + ":bacon_smokey";
	public final static String SCENT_BANANA = SCENTURIBASE + ":banana";
	public final static String SCENT_BANANA_SPLITS = SCENTURIBASE + ":banana_splits";
	public final static String SCENT_BASIL_HERD = SCENTURIBASE + ":basil_herd";
	public final static String SCENT_BEEF = SCENTURIBASE + ":beef";
	public final static String SCENT_BLACKCURRANT = SCENTURIBASE + ":blackcurrant";
	public final static String SCENT_BOILED_CABBAGE = SCENTURIBASE + ":boiled_cabbage";
	public final static String SCENT_BRANDY = SCENTURIBASE + ":brandy";
	public final static String SCENT_BREAD = SCENTURIBASE + ":bread";
	public final static String SCENT_BUBBLE_GUM = SCENTURIBASE + ":bubble_gum";
	public final static String SCENT_CAKE_SHOP = SCENTURIBASE + ":cake_shop";
	public final static String SCENT_CANDY_FLOSS = SCENTURIBASE + ":candy_floss";
	public final static String SCENT_CARAMEL_TOFFEE = SCENTURIBASE + ":caramel_toffee";
	public final static String SCENT_CARROT = SCENTURIBASE + ":carrot";
	public final static String SCENT_CELERY = SCENTURIBASE + ":celery";
	public final static String SCENT_CHERRY = SCENTURIBASE + ":cherry";
	public final static String SCENT_CHICKEN = SCENTURIBASE + ":chicken";
	public final static String SCENT_COCONUT = SCENTURIBASE + ":coconut";
	public final static String SCENT_CHOCOLATE_DARK = SCENTURIBASE + ":chocolate_dark";
	public final static String SCENT_CHOCOLATE_ORANGE = SCENTURIBASE + ":chocolate_orange";
	public final static String SCENT_CHRISTMAS_APPLE = SCENTURIBASE + ":christmas_apple";
	public final static String SCENT_CHRISTMAS_PUDDING = SCENTURIBASE + ":christmas_pudding";
	public final static String SCENT_CINNAMON = SCENTURIBASE + ":cinnamon";
	public final static String SCENT_COFFEE_CHOCOLATE = SCENTURIBASE + ":coffee_chocolate";
	public final static String SCENT_COFFEE_CREAM = SCENTURIBASE + ":coffee_cream";
	public final static String SCENT_COLA = SCENTURIBASE + ":cola";
	public final static String SCENT_CONFECTIONARY = SCENTURIBASE + ":confectionary";
	public final static String SCENT_COOKIE = SCENTURIBASE + ":cookie";
	public final static String SCENT_CORIANDER = SCENTURIBASE + ":coriander";
	public final static String SCENT_CRUSTY_BREAD = SCENTURIBASE + ":crusty_bread";
	public final static String SCENT_CURRY = SCENTURIBASE + ":curry";
	public final static String SCENT_FISHMARKET = SCENTURIBASE + ":fishmarket";
	public final static String SCENT_FRUIT_CAKE = SCENTURIBASE + ":fruit_cake";
	public final static String SCENT_FRUIT_PUNCH_BR_FRUITY_SWEETS = SCENTURIBASE + ":fruit_punch_br_fruity_sweets";
	public final static String SCENT_GARDEN_MINT = SCENTURIBASE + ":garden_mint";
	public final static String SCENT_GARLIC = SCENTURIBASE + ":garlic";
	public final static String SCENT_GINGERBREAD = SCENTURIBASE + ":gingerbread";
	public final static String SCENT_GRANNIES_KITCHEN = SCENTURIBASE + ":grannies_kitchen";
	public final static String SCENT_GRAPEFRUIT = SCENTURIBASE + ":grapefruit";
	public final static String SCENT_HERBS_MIXED = SCENTURIBASE + ":herbs_mixed";
	public final static String SCENT_HERRING = SCENTURIBASE + ":herring";
	public final static String SCENT_HONEY = SCENTURIBASE + ":honey";
	public final static String SCENT_HOT_APPLE_PIE = SCENTURIBASE + ":hot_apple_pie";
	public final static String SCENT_IRISH_CREAM = SCENTURIBASE + ":irish_cream";
	public final static String SCENT_JAMBALAYA = SCENTURIBASE + ":jambalaya";
	public final static String SCENT_JELLY_BABIES = SCENTURIBASE + ":jelly_babies";
	public final static String SCENT_KIWI_FRUIT = SCENTURIBASE + ":kiwi_fruit";
	public final static String SCENT_LIME_SPLASH = SCENTURIBASE + ":lime_splash";
	public final static String SCENT_LIQUORICE = SCENTURIBASE + ":liquorice";
	public final static String SCENT_MANGO_DELIGHT = SCENTURIBASE + ":mango_delight";
	public final static String SCENT_MELON = SCENTURIBASE + ":melon";
	public final static String SCENT_MINT_CHOCOLATE = SCENTURIBASE + ":mint_chocolate";
	public final static String SCENT_MULLED_WINE = SCENTURIBASE + ":mulled_wine";
	public final static String SCENT_NUTMEG = SCENTURIBASE + ":nutmeg";
	public final static String SCENT_ONION = SCENTURIBASE + ":onion";
	public final static String SCENT_ORANGE_CUPCAKE = SCENTURIBASE + ":orange_cupcake";
	public final static String SCENT_ORANGE_NF = SCENTURIBASE + ":orange_nf";
	public final static String SCENT_PASSION_FRUIT = SCENTURIBASE + ":passion_fruit";
	public final static String SCENT_PEACH_FLESH = SCENTURIBASE + ":peach_flesh";
	public final static String SCENT_PEAR_DROPS = SCENTURIBASE + ":pear_drops";
	public final static String SCENT_PEPPERMINT = SCENTURIBASE + ":peppermint";
	public final static String SCENT_PINA_COLADA = SCENTURIBASE + ":pina_colada";
	public final static String SCENT_PINEAPPLE = SCENTURIBASE + ":pineapple";
	public final static String SCENT_POPCORN = SCENTURIBASE + ":popcorn";
	public final static String SCENT_RASPBERRY = SCENTURIBASE + ":raspberry";
	public final static String SCENT_RASPBERRY_RIPPLES = SCENTURIBASE + ":raspberry_ripples";
	public final static String SCENT_RHUBARB = SCENTURIBASE + ":rhubarb";
	public final static String SCENT_ROSEMARY = SCENTURIBASE + ":rosemary";
	public final static String SCENT_RUM = SCENTURIBASE + ":rum";
	public final static String SCENT_SMOKED_FISH = SCENTURIBASE + ":smoked_fish";
	public final static String SCENT_SPICES_MIXED = SCENTURIBASE + ":spices_mixed";
	public final static String SCENT_STIR_FRY = SCENTURIBASE + ":stir_fry";
	public final static String SCENT_STRAWBERRY = SCENTURIBASE + ":strawberry";
	public final static String SCENT_SUGAR_SPICE_CHRISTMAS_AROMA = SCENTURIBASE + ":sugar_spice_christmas_aroma";
	public final static String SCENT_SWEET_SHERRY = SCENTURIBASE + ":sweet_sherry";
	public final static String SCENT_TANGERINE = SCENTURIBASE + ":tangerine";
	public final static String SCENT_TEA_LEAF = SCENTURIBASE + ":tea_leaf";
	public final static String SCENT_THAI_CURRY = SCENTURIBASE + ":thai_curry";
	public final static String SCENT_TOFFEE_APPLE = SCENTURIBASE + ":toffee_apple";
	public final static String SCENT_TOMATO_PLANT = SCENTURIBASE + ":tomato_plant";
	public final static String SCENT_WATERMELON = SCENTURIBASE + ":watermelon";
	public final static String SCENT_WHISKY = SCENTURIBASE + ":whisky";
	public final static String SCENT_WINE_OAK_CASK = SCENTURIBASE + ":wine_oak_cask";
	public final static String SCENT_VANILLA = SCENTURIBASE + ":vanilla";
	public final static String SCENT_WHISKY_SCOTCH = SCENTURIBASE + ":whisky_scotch";
	public final static String SCENT_ALPINE_LAUNDRY_POWDER = SCENTURIBASE + ":alpine_laundry_powder";
	public final static String SCENT_ALPINE = SCENTURIBASE + ":alpine";
	public final static String SCENT_AMULET = SCENTURIBASE + ":amulet";
	public final static String SCENT_AQUAWAVE = SCENTURIBASE + ":aquawave";
	public final static String SCENT_ARISTOCRAT = SCENTURIBASE + ":aristocrat";
	public final static String SCENT_BABY_POWDER = SCENTURIBASE + ":baby_powder";
	public final static String SCENT_BEAUTY_SOAP = SCENTURIBASE + ":beauty_soap";
	public final static String SCENT_BERGAMOT = SCENTURIBASE + ":bergamot";
	public final static String SCENT_BOILER_ROOM = SCENTURIBASE + ":boiler_room";
	public final static String SCENT_BOUQUET = SCENTURIBASE + ":bouquet";
	public final static String SCENT_BREWERY = SCENTURIBASE + ":brewery";
	public final static String SCENT_BURNING_PEAT = SCENTURIBASE + ":burning_peat";
	public final static String SCENT_BURNT_WOOD = SCENTURIBASE + ":burnt_wood";
	public final static String SCENT_CANNON = SCENTURIBASE + ":cannon";
	public final static String SCENT_CARNATION = SCENTURIBASE + ":carnation";
	public final static String SCENT_CARIBBEAN_HOLIDAY = SCENTURIBASE + ":caribbean_holiday";
	public final static String SCENT_CARBOLIC_SOAP = SCENTURIBASE + ":carbolic_soap";
	public final static String SCENT_CEDAR_WOOD = SCENTURIBASE + ":cedar_wood";
	public final static String SCENT_CHAMOMILE = SCENTURIBASE + ":chamomile";
	public final static String SCENT_CHRISTMAS_BERRIES = SCENTURIBASE + ":christmas_berries";
	public final static String SCENT_CHRISTMAS_TREE = SCENTURIBASE + ":christmas_tree";
	public final static String SCENT_CHRISTMAS_TIME = SCENTURIBASE + ":christmas_time";
	public final static String SCENT_CHURCH_INCENSE = SCENTURIBASE + ":church_incense";
	public final static String SCENT_CLOISTERS = SCENTURIBASE + ":cloisters";
	public final static String SCENT_CLINIC_HOSPITAL = SCENTURIBASE + ":clinic_hospital";
	public final static String SCENT_COAL_FACE = SCENTURIBASE + ":coal_face";
	public final static String SCENT_COAL_FIRE = SCENTURIBASE + ":coal_fire";
	public final static String SCENT_COAL_GAS = SCENTURIBASE + ":coal_gas";
	public final static String SCENT_COCOMANGO = SCENTURIBASE + ":cocomango";
	public final static String SCENT_CUBAN_CIGAR_SMOKE = SCENTURIBASE + ":cuban_cigar_smoke";
	public final static String SCENT_CUT_GRASS = SCENTURIBASE + ":cut_grass";
	public final static String SCENT_DEEP_HEAT = SCENTURIBASE + ":deep_heat";
	public final static String SCENT_DENTIST_CLOVE_OIL = SCENTURIBASE + ":dentist-clove_oil";
	public final static String SCENT_DINOSAUR = SCENTURIBASE + ":dinosaur";
	public final static String SCENT_DIRTY_LINEN = SCENTURIBASE + ":dirty_linen";
	public final static String SCENT_DRAGONS_BREATH = SCENTURIBASE + ":dragons_breath";
	public final static String SCENT_DRESSING_ROOM_FOOTBALL = SCENTURIBASE + ":dressing_room_football";
	public final static String SCENT_SCENT_OF_EARTHY = SCENTURIBASE + ":Scent of earthy";
	public final static String SCENT_EAU_DE_COLOGNE = SCENTURIBASE + ":eau_de_cologne";
	public final static String SCENT_EUCALYPTUS = SCENTURIBASE + ":eucalyptus";
	public final static String SCENT_EAU_DE_COLOGNE_FACTORY = SCENTURIBASE + ":eau_de_cologne_factory";
	public final static String SCENT_FARMYARD = SCENTURIBASE + ":farmyard";
	public final static String SCENT_FACTORY = SCENTURIBASE + ":factory";
	public final static String SCENT_FISH_MARKET = SCENTURIBASE + ":fish_market";
	public final static String SCENT_FLATULENCE = SCENTURIBASE + ":flatulence";
	public final static String SCENT_FOOTIE_PITCH = SCENTURIBASE + ":footie_pitch";
	public final static String SCENT_FOREST = SCENTURIBASE + ":forest";
	public final static String SCENT_FOX = SCENTURIBASE + ":fox";
	public final static String SCENT_FREESIA = SCENTURIBASE + ":freesia";
	public final static String SCENT_FRESH_AIR = SCENTURIBASE + ":fresh_air";
	public final static String SCENT_FROSTY = SCENTURIBASE + ":frosty";
	public final static String SCENT_GOLDEN_ONE = SCENTURIBASE + ":golden_one";
	public final static String SCENT_GRASS_HAY = SCENTURIBASE + ":grass_hay";
	public final static String SCENT_GUN_SMOKE = SCENTURIBASE + ":gun_smoke";
	public final static String SCENT_HAVANA_CIGAR = SCENTURIBASE + ":havana_cigar";
	public final static String SCENT_HAWAIIAN = SCENTURIBASE + ":hawaiian";
	public final static String SCENT_HEATHER_BRACKEN = SCENTURIBASE + ":heather_bracken";
	public final static String SCENT_HONEYSUCKLE = SCENTURIBASE + ":honeysuckle";
	public final static String SCENT_HOSPITAL_MODERN_DAY = SCENTURIBASE + ":hospital_modern_day";
	public final static String SCENT_HYACINTH = SCENTURIBASE + ":hyacinth";
	public final static String SCENT_INCENSE = SCENTURIBASE + ":incense";
	public final static String SCENT_IRON_SMELTING = SCENTURIBASE + ":iron_smelting";
	public final static String SCENT_JAGUAR_SPRAY = SCENTURIBASE + ":jaguar_spray";
	public final static String SCENT_JAPANESE_POW = SCENTURIBASE + ":japanese_pow";
	public final static String SCENT_LAVENDER = SCENTURIBASE + ":lavender";
	public final static String SCENT_LEATHER_CREAM = SCENTURIBASE + ":leather_cream";
	public final static String SCENT_LEATHER_HIDE = SCENTURIBASE + ":leather_hide";
	public final static String SCENT_LEMON_EUCALYPTUS_MINT = SCENTURIBASE + ":lemon_eucalyptus_mint";
	public final static String SCENT_MACHINE_OIL = SCENTURIBASE + ":machine_oil";
	public final static String SCENT_MAHOGANY = SCENTURIBASE + ":mahogany";
	public final static String SCENT_MAN_O_WAR = SCENTURIBASE + ":man_o_war";
	public final static String SCENT_MANURE_BR_METHANE = SCENTURIBASE + ":manure_br_methane";
	public final static String SCENT_MODERN_DAY_HOSPITAL = SCENTURIBASE + ":modern_day_hospital";
	public final static String SCENT_MOUNTAIN_HEATHER = SCENTURIBASE + ":mountain_heather";
	public final static String SCENT_MUMMY_EGYPTIAN = SCENTURIBASE + ":mummy_egyptian";
	public final static String SCENT_MUSTY = SCENTURIBASE + ":musty";
	public final static String SCENT_OAK = SCENTURIBASE + ":oak";
	public final static String SCENT_OLD_DRIFTER_SHIP = SCENTURIBASE + ":old_drifter_ship";
	public final static String SCENT_OLD_INN = SCENTURIBASE + ":old_inn";
	public final static String SCENT_OLD_RIVER = SCENTURIBASE + ":old_river";
	public final static String SCENT_OLD_SMITHY = SCENTURIBASE + ":old_smithy";
	public final static String SCENT_OUT_AT_SEA = SCENTURIBASE + ":out_at_sea";
	public final static String SCENT_OZONE = SCENTURIBASE + ":ozone";
	public final static String SCENT_PEAT = SCENTURIBASE + ":peat";
	public final static String SCENT_PENCIL_WOOD_SHAVINGS = SCENTURIBASE + ":pencil_wood_shavings";
	public final static String SCENT_PEONY = SCENTURIBASE + ":peony";
	public final static String SCENT_PHOSGENE_GAS = SCENTURIBASE + ":phosgene_gas";
	public final static String SCENT_PINE = SCENTURIBASE + ":pine";
	public final static String SCENT_PINEAPPLE_PLANTATION = SCENTURIBASE + ":pineapple_plantation";
	public final static String SCENT_PINE_HEATHER_PEAT = SCENTURIBASE + ":pine_heather_peat";
	public final static String SCENT_PIT_PONIES = SCENTURIBASE + ":pit_ponies";
	public final static String SCENT_POLISH_WAX = SCENTURIBASE + ":polish-wax";
	public final static String SCENT_POT_POURRI = SCENTURIBASE + ":pot-pourri";
	public final static String SCENT_RIVERBANK = SCENTURIBASE + ":riverbank";
	public final static String SCENT_RIVER_TROPICS = SCENTURIBASE + ":river_tropics";
	public final static String SCENT_ROPE_TAR = SCENTURIBASE + ":rope_tar";
	public final static String SCENT_ROSEWOOD = SCENTURIBASE + ":rosewood";
	public final static String SCENT_RUBBISH_ACRID = SCENTURIBASE + ":rubbish_acrid";
	public final static String SCENT_SANDALWOOD = SCENTURIBASE + ":sandalwood";
	public final static String SCENT_SANDALWOOD_BASIL = SCENTURIBASE + ":sandalwood_basil";
	public final static String SCENT_SEA_BREEZE = SCENTURIBASE + ":sea_breeze";
	public final static String SCENT_SEA_SHORE = SCENTURIBASE + ":sea_shore";
	public final static String SCENT_SHEBA = SCENTURIBASE + ":sheba";
	public final static String SCENT_SHIPS_CANNON = SCENTURIBASE + ":ships_cannon";
	public final static String SCENT_SNOWDROP = SCENTURIBASE + ":snowdrop";
	public final static String SCENT_SPORTS_CHANGING_ROOM = SCENTURIBASE + ":sports_changing_room";
	public final static String SCENT_STABLES_HORSES = SCENTURIBASE + ":stables_horses";
	public final static String SCENT_STARS_DRESSING_ROOM = SCENTURIBASE + ":stars_dressing_room";
	public final static String SCENT_STEAM_OIL_SHIPS = SCENTURIBASE + ":steam_oil_ships";
	public final static String SCENT_STEAM_OIL_TRAINS = SCENTURIBASE + ":steam_oil_trains";
	public final static String SCENT_STREET_1930S = SCENTURIBASE + ":street_1930s";
	public final static String SCENT_STREET_BOMB = SCENTURIBASE + ":street_bomb";
	public final static String SCENT_SUN_SAND_COCONUT = SCENTURIBASE + ":sun_sand_coconut";
	public final static String SCENT_SWAMP = SCENTURIBASE + ":swamp";
	public final static String SCENT_SWEATY_FEET = SCENTURIBASE + ":sweaty_feet";
	public final static String SCENT_SWEET_PEAS = SCENTURIBASE + ":sweet_peas";
	public final static String SCENT_TOBACCO_LEAF = SCENTURIBASE + ":tobacco_leaf";
	public final static String SCENT_TRAIN_SMOKE = SCENTURIBASE + ":train_smoke";
	public final static String SCENT_TROPHY_ROOM = SCENTURIBASE + ":trophy_room";
	public final static String SCENT_TROPICAL = SCENTURIBASE + ":tropical";
	public final static String SCENT_TROPICAL_RAIN_FOREST = SCENTURIBASE + ":tropical_rain_forest";
	public final static String SCENT_UNISEX_PERFUME = SCENTURIBASE + ":unisex_perfume";
	public final static String SCENT_URINE = SCENTURIBASE + ":urine";
	public final static String SCENT_USA_SWAMP = SCENTURIBASE + ":usa_swamp";
	public final static String SCENT_VICTORIAN_LAVENDER = SCENTURIBASE + ":victorian_lavender";
	public final static String SCENT_VIOLETS = SCENTURIBASE + ":violets";
	public final static String SCENT_VOLCANO = SCENTURIBASE + ":volcano";
	public final static String SCENT_VOMIT = SCENTURIBASE + ":vomit";
	public final static String SCENT_WALLFLOWER = SCENTURIBASE + ":wallflower";
	public final static String SCENT_WASHDAY = SCENTURIBASE + ":washday";
	public final static String SCENT_WILD_STAG = SCENTURIBASE + ":wild_stag";
	public final static String SCENT_WINE_CASK_OAK = SCENTURIBASE + ":wine_cask-oak";
	public final static String SCENT_WISTERIA = SCENTURIBASE + ":wisteria";
	public final static String SCENT_WOODSMOKE = SCENTURIBASE + ":woodsmoke";
	public final static String SCENT_YLANG_JASMIN_MYRRH = SCENTURIBASE + ":ylang_jasmin_myrrh";
	public final static String SCENT_YULETIDE = SCENTURIBASE + ":yuletide";
	public final static String SCENT_AFRICAN_RAIN = SCENTURIBASE + ":african_rain";
	public final static String SCENT_ALLEGRIA = SCENTURIBASE + ":allegria";
	public final static String SCENT_AMBER = SCENTURIBASE + ":amber";
	public final static String SCENT_APPLE_GREEN = SCENTURIBASE + ":apple_green";
	public final static String SCENT_ASAFOETIDA = SCENTURIBASE + ":asafoetida";
	public final static String SCENT_AUTUMN_FIELDS = SCENTURIBASE + ":autumn_fields";
	public final static String SCENT_AUTUMN_HARVEST = SCENTURIBASE + ":autumn_harvest";
	public final static String SCENT_BALSAM_FIR = SCENTURIBASE + ":balsam_fir";
	public final static String SCENT_BALSAM_FIR_NEEDLE = SCENTURIBASE + ":balsam_fir_needle";
	public final static String SCENT_BARNYARD = SCENTURIBASE + ":barnyard";
	public final static String SCENT_BEER = SCENTURIBASE + ":beer";
	public final static String SCENT_BENZOIN = SCENTURIBASE + ":benzoin";
	public final static String SCENT_BIRCH_TAR = SCENTURIBASE + ":birch_tar";
	public final static String SCENT_BIRTHDAY_CAKE = SCENTURIBASE + ":birthday_cake";
	public final static String SCENT_BLUEBERRY_COBBLER = SCENTURIBASE + ":blueberry_cobbler";
	public final static String SCENT_BOUQUET_OF_ROSES = SCENTURIBASE + ":bouquet_of_roses";
	public final static String SCENT_BUCHU = SCENTURIBASE + ":buchu";
	public final static String SCENT_BURNING_RUBBER = SCENTURIBASE + ":burning_rubber";
	public final static String SCENT_CACTUS_FLOWER = SCENTURIBASE + ":cactus_flower";
	public final static String SCENT_CADE = SCENTURIBASE + ":cade";
	public final static String SCENT_CAMPFIRE = SCENTURIBASE + ":campfire";
	public final static String SCENT_CAMPFIRE_SMOKE = SCENTURIBASE + ":campfire_smoke";
	public final static String SCENT_CAMPHOR = SCENTURIBASE + ":camphor";
	public final static String SCENT_CARIBBEAN_NIGHT = SCENTURIBASE + ":caribbean_night";
	public final static String SCENT_CEDAR = SCENTURIBASE + ":cedar";
	public final static String SCENT_CHAMPAGNE_STRAWBERRIES = SCENTURIBASE + ":champagne_strawberries";
	public final static String SCENT_CHANEL_NO5_TYPE = SCENTURIBASE + ":chanel_no5_type";
	public final static String SCENT_CHOCOLATE = SCENTURIBASE + ":chocolate";
	public final static String SCENT_CHRISTMAS_COOKIES = SCENTURIBASE + ":christmas_cookies";
	public final static String SCENT_CLEAN_COTTON = SCENTURIBASE + ":clean_cotton";
	public final static String SCENT_COTTON_CANDY = SCENTURIBASE + ":cotton_candy";
	public final static String SCENT_CREME_BRULE = SCENTURIBASE + ":creme_brule";
	public final static String SCENT_CYPRESS_GROVE = SCENTURIBASE + ":cypress_grove";
	public final static String SCENT_DUMPSTER = SCENTURIBASE + ":dumpster";
	public final static String SCENT_DUNG = SCENTURIBASE + ":dung";
	public final static String SCENT_EASTER_LILLIES = SCENTURIBASE + ":easter_lillies";
	public final static String SCENT_EGG_NOG_2 = SCENTURIBASE + ":egg_nog_2";
	public final static String SCENT_EUCALYPTUS_DIVES = SCENTURIBASE + ":eucalyptus_dives";
	public final static String SCENT_EVERGREEN = SCENTURIBASE + ":evergreen";
	public final static String SCENT_EXHAUST = SCENTURIBASE + ":exhaust";
	public final static String SCENT_FISH = SCENTURIBASE + ":fish";
	public final static String SCENT_FOREST_RAIN = SCENTURIBASE + ":forest_rain";
	public final static String SCENT_FORGET_ME_NOT = SCENTURIBASE + ":forget-me-not";
	public final static String SCENT_FRANGIPANI = SCENTURIBASE + ":frangipani";
	public final static String SCENT_FRENCH_FRIES = SCENTURIBASE + ":french_fries";
	public final static String SCENT_FRESH_BREAD = SCENTURIBASE + ":fresh_bread";
	public final static String SCENT_FRESH_CUT_GRASS = SCENTURIBASE + ":fresh_cut_grass";
	public final static String SCENT_FRESH_LAUNDRY = SCENTURIBASE + ":fresh_laundry";
	public final static String SCENT_FRYING_BACON = SCENTURIBASE + ":frying_bacon";
	public final static String SCENT_FUDGE_BROWNIE = SCENTURIBASE + ":fudge_brownie";
	public final static String SCENT_GARDENIA = SCENTURIBASE + ":gardenia";
	public final static String SCENT_GRANDMAS_ATTIC = SCENTURIBASE + ":grandmas_attic";
	public final static String SCENT_HALLOWEEN_GREASEPAINT = SCENTURIBASE + ":halloween_greasepaint";
	public final static String SCENT_HAWAIAN_TREAT = SCENTURIBASE + ":hawaian_treat";
	public final static String SCENT_INDIAN_SUMMER = SCENTURIBASE + ":indian_summer";
	public final static String SCENT_JET_FUEL = SCENTURIBASE + ":jet_fuel";
	public final static String SCENT_JUNIPER_BERRY = SCENTURIBASE + ":juniper_berry";
	public final static String SCENT_LEATHER = SCENTURIBASE + ":leather";
	public final static String SCENT_LOTUS = SCENTURIBASE + ":lotus";
	public final static String SCENT_MANGO_MANDARIN = SCENTURIBASE + ":mango_mandarin";
	public final static String SCENT_MAPLE_SYRUP = SCENTURIBASE + ":maple_syrup";
	public final static String SCENT_MILDEW = SCENTURIBASE + ":mildew";
	public final static String SCENT_MOTHER_EARTH = SCENTURIBASE + ":mother_earth";
	public final static String SCENT_MUSK = SCENTURIBASE + ":musk";
	public final static String SCENT_NEW_MOWN_GRASS_2 = SCENTURIBASE + ":new_mown_grass_2";
	public final static String SCENT_NEW_MOWN_GRASS_3 = SCENTURIBASE + ":new_mown_grass_3";
	public final static String SCENT_OAK_MOSS = SCENTURIBASE + ":oak_moss";
	public final static String SCENT_OPEN_FIREPLACE = SCENTURIBASE + ":open_fireplace";
	public final static String SCENT_PALMAROSA = SCENTURIBASE + ":palmarosa";
	public final static String SCENT_PANCAKES_MAPLE_SYRUP = SCENTURIBASE + ":pancakes_maple_syrup";
	public final static String SCENT_PATCHOULI = SCENTURIBASE + ":patchouli";
	public final static String SCENT_PECAN_PIE = SCENTURIBASE + ":pecan_pie";
	public final static String SCENT_RAIN_FOREST = SCENTURIBASE + ":rain_forest";
	public final static String SCENT_RICH_POTTING_SOIL = SCENTURIBASE + ":rich_potting_soil";
	public final static String SCENT_ROASTED_CHICKEN = SCENTURIBASE + ":roasted_chicken";
	public final static String SCENT_SAGE_DALMATIAN = SCENTURIBASE + ":sage_dalmatian";
	public final static String SCENT_SEAWEED = SCENTURIBASE + ":seaweed";
	public final static String SCENT_SPANISH_MOSS = SCENTURIBASE + ":spanish_moss";
	public final static String SCENT_SPRING_BOUQUET = SCENTURIBASE + ":spring_bouquet";
	public final static String SCENT_SUNTAN = SCENTURIBASE + ":suntan";
	public final static String SCENT_THYME_BORNEOL = SCENTURIBASE + ":thyme_borneol";
	public final static String SCENT_TOMATO_VINE = SCENTURIBASE + ":tomato_vine";
	public final static String SCENT_TUBEROSE = SCENTURIBASE + ":tuberose";
	public final static String SCENT_VIOLET = SCENTURIBASE + ":violet";
	public final static String SCENT_WARMING_GINGER = SCENTURIBASE + ":warming_ginger";
	public final static String SCENT_YLANG_YLANG = SCENTURIBASE + ":ylang_ylang";
	
	static {
		scentTable_.add(SCENT_ROSE);
		scentTable_.add(SCENT_ACACIA);
		scentTable_.add(SCENT_CHRYSANTHEMUM);
		scentTable_.add(SCENT_LILAC);
		scentTable_.add(SCENT_MINT);
		scentTable_.add(SCENT_JASMINE);
		scentTable_.add(SCENT_PINE_TREE);
		scentTable_.add(SCENT_ORANGE);
		scentTable_.add(SCENT_GRAPE);
		scentTable_.add(SCENT_ALMONDS);
		scentTable_.add(SCENT_AMARETTO);
		scentTable_.add(SCENT_APPLES_GREEN);
		scentTable_.add(SCENT_APPLES_RED);
		scentTable_.add(SCENT_BACON);
		scentTable_.add(SCENT_BACON_SMOKEY);
		scentTable_.add(SCENT_BANANA);
		scentTable_.add(SCENT_BANANA_SPLITS);
		scentTable_.add(SCENT_BASIL_HERD);
		scentTable_.add(SCENT_BEEF);
		scentTable_.add(SCENT_BLACKCURRANT);
		scentTable_.add(SCENT_BOILED_CABBAGE);
		scentTable_.add(SCENT_BRANDY);
		scentTable_.add(SCENT_BREAD);
		scentTable_.add(SCENT_BUBBLE_GUM);
		scentTable_.add(SCENT_CAKE_SHOP);
		scentTable_.add(SCENT_CANDY_FLOSS);
		scentTable_.add(SCENT_CARAMEL_TOFFEE);
		scentTable_.add(SCENT_CARROT);
		scentTable_.add(SCENT_CELERY);
		scentTable_.add(SCENT_CHERRY);
		scentTable_.add(SCENT_CHICKEN);
		scentTable_.add(SCENT_COCONUT);
		scentTable_.add(SCENT_CHOCOLATE_DARK);
		scentTable_.add(SCENT_CHOCOLATE_ORANGE);
		scentTable_.add(SCENT_CHRISTMAS_APPLE);
		scentTable_.add(SCENT_CHRISTMAS_PUDDING);
		scentTable_.add(SCENT_CINNAMON);
		scentTable_.add(SCENT_COFFEE_CHOCOLATE);
		scentTable_.add(SCENT_COFFEE_CREAM);
		scentTable_.add(SCENT_COLA);
		scentTable_.add(SCENT_CONFECTIONARY);
		scentTable_.add(SCENT_COOKIE);
		scentTable_.add(SCENT_CORIANDER);
		scentTable_.add(SCENT_CRUSTY_BREAD);
		scentTable_.add(SCENT_CURRY);
		scentTable_.add(SCENT_FISHMARKET);
		scentTable_.add(SCENT_FRUIT_CAKE);
		scentTable_.add(SCENT_FRUIT_PUNCH_BR_FRUITY_SWEETS);
		scentTable_.add(SCENT_GARDEN_MINT);
		scentTable_.add(SCENT_GARLIC);
		scentTable_.add(SCENT_GINGERBREAD);
		scentTable_.add(SCENT_GRANNIES_KITCHEN);
		scentTable_.add(SCENT_GRAPEFRUIT);
		scentTable_.add(SCENT_HERBS_MIXED);
		scentTable_.add(SCENT_HERRING);
		scentTable_.add(SCENT_HONEY);
		scentTable_.add(SCENT_HOT_APPLE_PIE);
		scentTable_.add(SCENT_IRISH_CREAM);
		scentTable_.add(SCENT_JAMBALAYA);
		scentTable_.add(SCENT_JELLY_BABIES);
		scentTable_.add(SCENT_KIWI_FRUIT);
		scentTable_.add(SCENT_LIME_SPLASH);
		scentTable_.add(SCENT_LIQUORICE);
		scentTable_.add(SCENT_MANGO_DELIGHT);
		scentTable_.add(SCENT_MELON);
		scentTable_.add(SCENT_MINT_CHOCOLATE);
		scentTable_.add(SCENT_MULLED_WINE);
		scentTable_.add(SCENT_NUTMEG);
		scentTable_.add(SCENT_ONION);
		scentTable_.add(SCENT_ORANGE_CUPCAKE);
		scentTable_.add(SCENT_ORANGE_NF);
		scentTable_.add(SCENT_PASSION_FRUIT);
		scentTable_.add(SCENT_PEACH_FLESH);
		scentTable_.add(SCENT_PEAR_DROPS);
		scentTable_.add(SCENT_PEPPERMINT);
		scentTable_.add(SCENT_PINA_COLADA);
		scentTable_.add(SCENT_PINEAPPLE);
		scentTable_.add(SCENT_POPCORN);
		scentTable_.add(SCENT_RASPBERRY);
		scentTable_.add(SCENT_RASPBERRY_RIPPLES);
		scentTable_.add(SCENT_RHUBARB);
		scentTable_.add(SCENT_ROSEMARY);
		scentTable_.add(SCENT_RUM);
		scentTable_.add(SCENT_SMOKED_FISH);
		scentTable_.add(SCENT_SPICES_MIXED);
		scentTable_.add(SCENT_STIR_FRY);
		scentTable_.add(SCENT_STRAWBERRY);
		scentTable_.add(SCENT_SUGAR_SPICE_CHRISTMAS_AROMA);
		scentTable_.add(SCENT_SWEET_SHERRY);
		scentTable_.add(SCENT_TANGERINE);
		scentTable_.add(SCENT_TEA_LEAF);
		scentTable_.add(SCENT_THAI_CURRY);
		scentTable_.add(SCENT_TOFFEE_APPLE);
		scentTable_.add(SCENT_TOMATO_PLANT);
		scentTable_.add(SCENT_WATERMELON);
		scentTable_.add(SCENT_WHISKY);
		scentTable_.add(SCENT_WINE_OAK_CASK);
		scentTable_.add(SCENT_VANILLA);
		scentTable_.add(SCENT_WHISKY_SCOTCH);
		scentTable_.add(SCENT_ALPINE_LAUNDRY_POWDER);
		scentTable_.add(SCENT_ALPINE);
		scentTable_.add(SCENT_AMULET);
		scentTable_.add(SCENT_AQUAWAVE);
		scentTable_.add(SCENT_ARISTOCRAT);
		scentTable_.add(SCENT_BABY_POWDER);
		scentTable_.add(SCENT_BEAUTY_SOAP);
		scentTable_.add(SCENT_BERGAMOT);
		scentTable_.add(SCENT_BOILER_ROOM);
		scentTable_.add(SCENT_BOUQUET);
		scentTable_.add(SCENT_BREWERY);
		scentTable_.add(SCENT_BURNING_PEAT);
		scentTable_.add(SCENT_BURNT_WOOD);
		scentTable_.add(SCENT_CANNON);
		scentTable_.add(SCENT_CARNATION);
		scentTable_.add(SCENT_CARIBBEAN_HOLIDAY);
		scentTable_.add(SCENT_CARBOLIC_SOAP);
		scentTable_.add(SCENT_CEDAR_WOOD);
		scentTable_.add(SCENT_CHAMOMILE);
		scentTable_.add(SCENT_CHRISTMAS_BERRIES);
		scentTable_.add(SCENT_CHRISTMAS_TREE);
		scentTable_.add(SCENT_CHRISTMAS_TIME);
		scentTable_.add(SCENT_CHURCH_INCENSE);
		scentTable_.add(SCENT_CLOISTERS);
		scentTable_.add(SCENT_CLINIC_HOSPITAL);
		scentTable_.add(SCENT_COAL_FACE);
		scentTable_.add(SCENT_COAL_FIRE);
		scentTable_.add(SCENT_COAL_GAS);
		scentTable_.add(SCENT_COCOMANGO);
		scentTable_.add(SCENT_CUBAN_CIGAR_SMOKE);
		scentTable_.add(SCENT_CUT_GRASS);
		scentTable_.add(SCENT_DEEP_HEAT);
		scentTable_.add(SCENT_DENTIST_CLOVE_OIL);
		scentTable_.add(SCENT_DINOSAUR);
		scentTable_.add(SCENT_DIRTY_LINEN);
		scentTable_.add(SCENT_DRAGONS_BREATH);
		scentTable_.add(SCENT_DRESSING_ROOM_FOOTBALL);
		scentTable_.add(SCENT_SCENT_OF_EARTHY);
		scentTable_.add(SCENT_EAU_DE_COLOGNE);
		scentTable_.add(SCENT_EUCALYPTUS);
		scentTable_.add(SCENT_EAU_DE_COLOGNE_FACTORY);
		scentTable_.add(SCENT_FARMYARD);
		scentTable_.add(SCENT_FACTORY);
		scentTable_.add(SCENT_FISH_MARKET);
		scentTable_.add(SCENT_FLATULENCE);
		scentTable_.add(SCENT_FOOTIE_PITCH);
		scentTable_.add(SCENT_FOREST);
		scentTable_.add(SCENT_FOX);
		scentTable_.add(SCENT_FREESIA);
		scentTable_.add(SCENT_FRESH_AIR);
		scentTable_.add(SCENT_FROSTY);
		scentTable_.add(SCENT_GOLDEN_ONE);
		scentTable_.add(SCENT_GRASS_HAY);
		scentTable_.add(SCENT_GUN_SMOKE);
		scentTable_.add(SCENT_HAVANA_CIGAR);
		scentTable_.add(SCENT_HAWAIIAN);
		scentTable_.add(SCENT_HEATHER_BRACKEN);
		scentTable_.add(SCENT_HONEYSUCKLE);
		scentTable_.add(SCENT_HOSPITAL_MODERN_DAY);
		scentTable_.add(SCENT_HYACINTH);
		scentTable_.add(SCENT_INCENSE);
		scentTable_.add(SCENT_IRON_SMELTING);
		scentTable_.add(SCENT_JAGUAR_SPRAY);
		scentTable_.add(SCENT_JAPANESE_POW);
		scentTable_.add(SCENT_LAVENDER);
		scentTable_.add(SCENT_LEATHER_CREAM);
		scentTable_.add(SCENT_LEATHER_HIDE);
		scentTable_.add(SCENT_LEMON_EUCALYPTUS_MINT);
		scentTable_.add(SCENT_MACHINE_OIL);
		scentTable_.add(SCENT_MAHOGANY);
		scentTable_.add(SCENT_MAN_O_WAR);
		scentTable_.add(SCENT_MANURE_BR_METHANE);
		scentTable_.add(SCENT_MODERN_DAY_HOSPITAL);
		scentTable_.add(SCENT_MOUNTAIN_HEATHER);
		scentTable_.add(SCENT_MUMMY_EGYPTIAN);
		scentTable_.add(SCENT_MUSTY);
		scentTable_.add(SCENT_OAK);
		scentTable_.add(SCENT_OLD_DRIFTER_SHIP);
		scentTable_.add(SCENT_OLD_INN);
		scentTable_.add(SCENT_OLD_RIVER);
		scentTable_.add(SCENT_OLD_SMITHY);
		scentTable_.add(SCENT_OUT_AT_SEA);
		scentTable_.add(SCENT_OZONE);
		scentTable_.add(SCENT_PEAT);
		scentTable_.add(SCENT_PENCIL_WOOD_SHAVINGS);
		scentTable_.add(SCENT_PEONY);
		scentTable_.add(SCENT_PHOSGENE_GAS);
		scentTable_.add(SCENT_PINE);
		scentTable_.add(SCENT_PINEAPPLE_PLANTATION);
		scentTable_.add(SCENT_PINE_HEATHER_PEAT);
		scentTable_.add(SCENT_PIT_PONIES);
		scentTable_.add(SCENT_POLISH_WAX);
		scentTable_.add(SCENT_POT_POURRI);
		scentTable_.add(SCENT_RIVERBANK);
		scentTable_.add(SCENT_RIVER_TROPICS);
		scentTable_.add(SCENT_ROPE_TAR);
		scentTable_.add(SCENT_ROSEWOOD);
		scentTable_.add(SCENT_RUBBISH_ACRID);
		scentTable_.add(SCENT_SANDALWOOD);
		scentTable_.add(SCENT_SANDALWOOD_BASIL);
		scentTable_.add(SCENT_SEA_BREEZE);
		scentTable_.add(SCENT_SEA_SHORE);
		scentTable_.add(SCENT_SHEBA);
		scentTable_.add(SCENT_SHIPS_CANNON);
		scentTable_.add(SCENT_SNOWDROP);
		scentTable_.add(SCENT_SPORTS_CHANGING_ROOM);
		scentTable_.add(SCENT_STABLES_HORSES);
		scentTable_.add(SCENT_STARS_DRESSING_ROOM);
		scentTable_.add(SCENT_STEAM_OIL_SHIPS);
		scentTable_.add(SCENT_STEAM_OIL_TRAINS);
		scentTable_.add(SCENT_STREET_1930S);
		scentTable_.add(SCENT_STREET_BOMB);
		scentTable_.add(SCENT_SUN_SAND_COCONUT);
		scentTable_.add(SCENT_SWAMP);
		scentTable_.add(SCENT_SWEATY_FEET);
		scentTable_.add(SCENT_SWEET_PEAS);
		scentTable_.add(SCENT_TOBACCO_LEAF);
		scentTable_.add(SCENT_TRAIN_SMOKE);
		scentTable_.add(SCENT_TROPHY_ROOM);
		scentTable_.add(SCENT_TROPICAL);
		scentTable_.add(SCENT_TROPICAL_RAIN_FOREST);
		scentTable_.add(SCENT_UNISEX_PERFUME);
		scentTable_.add(SCENT_URINE);
		scentTable_.add(SCENT_USA_SWAMP);
		scentTable_.add(SCENT_VICTORIAN_LAVENDER);
		scentTable_.add(SCENT_VIOLETS);
		scentTable_.add(SCENT_VOLCANO);
		scentTable_.add(SCENT_VOMIT);
		scentTable_.add(SCENT_WALLFLOWER);
		scentTable_.add(SCENT_WASHDAY);
		scentTable_.add(SCENT_WILD_STAG);
		scentTable_.add(SCENT_WINE_CASK_OAK);
		scentTable_.add(SCENT_WISTERIA);
		scentTable_.add(SCENT_WOODSMOKE);
		scentTable_.add(SCENT_YLANG_JASMIN_MYRRH);
		scentTable_.add(SCENT_YULETIDE);
		scentTable_.add(SCENT_AFRICAN_RAIN);
		scentTable_.add(SCENT_ALLEGRIA);
		scentTable_.add(SCENT_AMBER);
		scentTable_.add(SCENT_APPLE_GREEN);
		scentTable_.add(SCENT_ASAFOETIDA);
		scentTable_.add(SCENT_AUTUMN_FIELDS);
		scentTable_.add(SCENT_AUTUMN_HARVEST);
		scentTable_.add(SCENT_BALSAM_FIR);
		scentTable_.add(SCENT_BALSAM_FIR_NEEDLE);
		scentTable_.add(SCENT_BARNYARD);
		scentTable_.add(SCENT_BEER);
		scentTable_.add(SCENT_BENZOIN);
		scentTable_.add(SCENT_BIRCH_TAR);
		scentTable_.add(SCENT_BIRTHDAY_CAKE);
		scentTable_.add(SCENT_BLUEBERRY_COBBLER);
		scentTable_.add(SCENT_BOUQUET_OF_ROSES);
		scentTable_.add(SCENT_BUCHU);
		scentTable_.add(SCENT_BURNING_RUBBER);
		scentTable_.add(SCENT_CACTUS_FLOWER);
		scentTable_.add(SCENT_CADE);
		scentTable_.add(SCENT_CAMPFIRE);
		scentTable_.add(SCENT_CAMPFIRE_SMOKE);
		scentTable_.add(SCENT_CAMPHOR);
		scentTable_.add(SCENT_CARIBBEAN_NIGHT);
		scentTable_.add(SCENT_CEDAR);
		scentTable_.add(SCENT_CHAMPAGNE_STRAWBERRIES);
		scentTable_.add(SCENT_CHANEL_NO5_TYPE);
		scentTable_.add(SCENT_CHOCOLATE);
		scentTable_.add(SCENT_CHRISTMAS_COOKIES);
		scentTable_.add(SCENT_CLEAN_COTTON);
		scentTable_.add(SCENT_COTTON_CANDY);
		scentTable_.add(SCENT_CREME_BRULE);
		scentTable_.add(SCENT_CYPRESS_GROVE);
		scentTable_.add(SCENT_DUMPSTER);
		scentTable_.add(SCENT_DUNG);
		scentTable_.add(SCENT_EASTER_LILLIES);
		scentTable_.add(SCENT_EGG_NOG_2);
		scentTable_.add(SCENT_EUCALYPTUS_DIVES);
		scentTable_.add(SCENT_EVERGREEN);
		scentTable_.add(SCENT_EXHAUST);
		scentTable_.add(SCENT_FISH);
		scentTable_.add(SCENT_FOREST_RAIN);
		scentTable_.add(SCENT_FORGET_ME_NOT);
		scentTable_.add(SCENT_FRANGIPANI);
		scentTable_.add(SCENT_FRENCH_FRIES);
		scentTable_.add(SCENT_FRESH_BREAD);
		scentTable_.add(SCENT_FRESH_CUT_GRASS);
		scentTable_.add(SCENT_FRESH_LAUNDRY);
		scentTable_.add(SCENT_FRYING_BACON);
		scentTable_.add(SCENT_FUDGE_BROWNIE);
		scentTable_.add(SCENT_GARDENIA);
		scentTable_.add(SCENT_GRANDMAS_ATTIC);
		scentTable_.add(SCENT_HALLOWEEN_GREASEPAINT);
		scentTable_.add(SCENT_HAWAIAN_TREAT);
		scentTable_.add(SCENT_INDIAN_SUMMER);
		scentTable_.add(SCENT_JET_FUEL);
		scentTable_.add(SCENT_JUNIPER_BERRY);
		scentTable_.add(SCENT_LEATHER);
		scentTable_.add(SCENT_LOTUS);
		scentTable_.add(SCENT_MANGO_MANDARIN);
		scentTable_.add(SCENT_MAPLE_SYRUP);
		scentTable_.add(SCENT_MILDEW);
		scentTable_.add(SCENT_MOTHER_EARTH);
		scentTable_.add(SCENT_MUSK);
		scentTable_.add(SCENT_NEW_MOWN_GRASS_2);
		scentTable_.add(SCENT_NEW_MOWN_GRASS_3);
		scentTable_.add(SCENT_OAK_MOSS);
		scentTable_.add(SCENT_OPEN_FIREPLACE);
		scentTable_.add(SCENT_PALMAROSA);
		scentTable_.add(SCENT_PANCAKES_MAPLE_SYRUP);
		scentTable_.add(SCENT_PATCHOULI);
		scentTable_.add(SCENT_PECAN_PIE);
		scentTable_.add(SCENT_RAIN_FOREST);
		scentTable_.add(SCENT_RICH_POTTING_SOIL);
		scentTable_.add(SCENT_ROASTED_CHICKEN);
		scentTable_.add(SCENT_SAGE_DALMATIAN);
		scentTable_.add(SCENT_SEAWEED);
		scentTable_.add(SCENT_SPANISH_MOSS);
		scentTable_.add(SCENT_SPRING_BOUQUET);
		scentTable_.add(SCENT_SUNTAN);
		scentTable_.add(SCENT_THYME_BORNEOL);
		scentTable_.add(SCENT_TOMATO_VINE);
		scentTable_.add(SCENT_TUBEROSE);
		scentTable_.add(SCENT_VIOLET);
		scentTable_.add(SCENT_WARMING_GINGER);
		scentTable_.add(SCENT_YLANG_YLANG);
	}
	
	public static Vector<String> getScentTable() {
		return scentTable_;
	}
	
	public static boolean containsScent(String scentURI) {
		return scentTable_.contains(scentURI);
	}
	
	// A.2.6 SprayingTypeCS
	private static Vector<String> sprayingTypeTable_ =  new Vector<String>();
	public final static String SPRAYINGTYPEURIBASE = "urn:mpeg:mpeg-v:01-SI-SprayingTypeCS-NS";
	public final static String SPRAYINGTYPE_WATER = SPRAYINGTYPEURIBASE + ":water";
	
	static {
		sprayingTypeTable_.add(SPRAYINGTYPE_WATER);
	}
	
	public static Vector<String> getSprayingTypeTable() {
		return sprayingTypeTable_;
	}
	
	public static boolean containsSprayingType(String sprayingTypeURI) {
		return sprayingTypeTable_.contains(sprayingTypeURI);
	}
}
